### ISSUE TITLE
How to combine functions and firestore?

### ISSUE THREAD

**Issue by vongohren** [GoogleCloudPlatform/functions-framework-nodejs#101]
I have been scouring the internet to try to figure out how to setup a development env for myself, where I have one function, triggering a firestore set document, then another function listening on firestore events and doing something smart!

1. I want to be able to develop on both functions in some kind of way.
2. I want to be able to run some kind of debugger towards the function being developed on.
3. I want to be able to watch the code for faster iterations.

Right now Im able to run firebase emulators:start and then that runs firestore and functions. Which connects everything and it acctually works. But I cannot see any possibility for criteria 2. Asking on their lib: https://github.com/firebase/firebase-tools/issues/1667

Im able to get this lib to run with inspect and watch, but not able to connect to to the firestore at all.

So since firebase and google is the same company, why are they talking past each other and creating a fragmented documentation, particularly on functions.

I would love to see a simple, yet flexible way to be able to match all criterias in this issue
If someone have done that already, please let me know!
If not, lets figure out how, and document it.

**Comment by grant** [comment]
@vongohren I'm not sure what the exact question is. Cloud Functions for Firebase integrates more closely with Firebase products and tools. There's nothing stopping us from using their APIs like [Firestore](https://github.com/googleapis/nodejs-firestore).

The simple way to answer your questions is to create a `npm` package that can be use everywhere. You can use the Node debugger like normal.

What specific questions about the Functions Framework do you have?

**Comment by vongohren** [comment]
So functions and firebase functions are the same thing. Yes firebase emulator have made it more tightly coupled but im very happy with not tightly coupled, as you guys provide. Talking from a locally development perspective

In this issue, https://github.com/firebase/firebase-tools/issues/1667 he does answer my question but from the firebase side.

I raised this issue here to see if you guys did have an example on how to run it locally with firestore. Because the answer in the other issue, was something I tried, and I did not get it working the first time, have not tried again. And it is not clear in the docs of this tool, how to run things locally and be able to trigger onUpdate and onCreate functions with this tool.

Does it make more sense 😁?

**Comment by grant** [comment]
Sorry, what is the issue?
You cannot trigger onUpdate or onCreate functions with this tool.

**Comment by vongohren** [comment]
I did not know I was speaking 🈲?

Let put it in a different way.
I can run function A which is a http function with this tool.
I can run function B which is written as a onCreate function, with this tool.
These two functions run side by side.

Function A can use a firestore emulator to store and get data right? By triggering the https function which has firestore code inside of it? It can also run towards a live database?

Since the emulator is running, thanks to the firebase tool, I woudl pressume I could connect the function B to the emulator somehow. I would pressume that since function A triggers a create, it might be possible for function B to react, because they are connected to the same emulator?

Or since you are saying "you cannot trigger onUpdate or onCreate functions with this tool" it is not possible now? Will never be? And this case is not worth supporting?

**Comment by grant** [comment]
Hey @vongohren, I'm sorry, but I don't understand what issue we are reporting with the Functions Framework. We have a few guides on things like debugging, watching, etc:

- [Debugging](https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/docs/debugging.md)
- [Watching source code changes](https://github.com/googlesamples/functions-as-a-service)

---

Aside, I think this developer issue is related to the firestore emulator and can be followed-up here:
https://github.com/firebase/firebase-tools/issues/1360

As such, I'll close issue until debugging with firebase tools is fixed.
