### ISSUE TITLE
Optionally use koajs

### ISSUE THREAD

**Issue by rynz** [GoogleCloudPlatform/functions-framework-nodejs#105]
@tj also created [koajs](https://koajs.com/). It would be nice to be able to switch out `expressjs` for `koajs` with GCF.
What are your thoughts on adding this as an optional feature?

**Comment by grant** [comment]
Hey @rynz,
Do you use Koajs right now? Can you provide some more background?
In my personal experience, I haven't has many issues with Express, but would like to hear more details as to your thoughts.

Perhaps we could write a blogpost on deploying Koa apps on GCP.

**Comment by rynz** [comment]
Hey @grant,
I've been using koajs for many years now, there's a great explanation as to the differences: https://github.com/koajs/koa/blob/master/docs/koa-vs-express.md

There was a decision made early in its development not to make it "Express 4.0" because "the design is fundamentally much different". Originally it was created with `generators`, then later adopted `promises`.

What I personally enjoy about koajs is that it is a thin abstraction of nodejs' `http` modules and is not bundled with any middleware, for example, routing is not included but there are [many to choose from](https://github.com/koajs/koa/wiki#routing-and-mounting). This makes it a great candidate for serverless applications, particularly Cloud Run and is something I am currently using on GCP.

Because of its design and use of `promises`, you can create a single middleware to handle exceptions thrown at any point of the application/dependencies, for example:

```
app.use(async (ctx, next) => {
  try {
    await next()
  } catch (err) {
    ctx.app.emit('error', err, ctx)
    ctx.body =
      err instanceof HttpError
        ? { code: err.code, message: err.message }
        : { code: 9000, message: err.expose ? err.message : 'Kaboom!' }
    ctx.status = err.status || 500
  }
})

app.use(async (ctx, next) => {
  if (ctx.path !== '/') {
    await next()
    return
  }
  ctx.body = { hello: 'world' }
})

app.use(async (ctx, next) => {
  if (ctx.path !== '/401') {
    await next()
    return
  }
  throw new UnauthorizedError(19, 'Rwar')
})
```

This allows me to have a single `try/catch` that formats a user-facing `HttpError`, which can be exported as it's own middleware module with its own unit tests etc.

I would be more than happy to help you with a blogpost, particularly with Cloud Run Koa apps. I'm quite confident incorporating koajs as a replacement option to expressjs in GCF would be beneficial too, particularly if it was designed in a way to complement the default `exports.helloWorld` eg: `module.exports = [cors, helloWorld]` where the exported array is middleware.

**Comment by grant** [comment]
So, we can't really support Koa with this repository. We decided to use Express. We'd need to create a new repo if we want to use Koa (on Cloud Functions).

Cloud Run is a fine option as an alternative.

I think the real ask is for how do I use Koa with Google Cloud.
It should be pretty easy with Cloud Run. In the future perhaps we could support multiple frameworks for Google Cloud Functions, but that's not really in demand right now.

I'm going to close this issue, but feel free to keep commenting and adding suggestions.
