### ISSUE TITLE
Support Node 12

### ISSUE THREAD

**Issue by rajveermalviya** [GoogleCloudPlatform/functions-framework-nodejs#110]
Node 12 is LTS since [October 21](https://nodejs.org/en/about/releases/) so it's time to provide support for latest LTS runtime.

**Comment by grant** [comment]
This framework supports Node 12. It isn't yet an option in Google Cloud Functions.

Here's a blogpost on using Node 12 with the FF:

https://medium.com/google-cloud/node-12-functions-on-cloud-run-d891dd93c7c8

What issue are you running into with this framework?

**Comment by rajveermalviya** [comment]
Oh my bad, there is not any issue with the project.
I just meant to get support for GCF.

Thanks, I see only solution right now would be to use Cloud Run.

Closing the issue.

**Comment by grant** [comment]
Yeah, the relationship between this open source library is the GCP product of Cloud Functions is not always clear.

The standard way to file feature requests for the product is here:
https://cloud.google.com/functions/docs/getting-support#file_bugs_or_feature_requests

I'll get the GCF team to support the option of Node 12, but it may take a bit.
