### ISSUE TITLE
Cloud Run port

### ISSUE THREAD

**Issue by Mistic92** [GoogleCloudPlatform/functions-framework-nodejs#12]
How to pass PORT env to use with Cloud Run? I can't use env variable in package.json.

**Comment by stew-r** [comment]
You shouldn't need to pass the PORT. Cloud Run sets the PORT environment variable automatically. The framework should pick it up automatically.

The [logic](https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/565230c0a8efd8183ecea8dc12d4754eecbecc5f/src/index.ts#L47) within the Functions Framework is as follows

1. Check for --port command-line argument. If not found...
2. Check for PORT environment variable. This should be set by default on Cloud Run. If not found...
3. Default to port 8080

**Comment by Mistic92** [comment]
Thank you for explaining. So I see I have problem with typescript and dockerfile

**Comment by grant** [comment]
The port configuration is documented here:

https://github.com/GoogleCloudPlatform/functions-framework-nodejs#configure-the-functions-framework
