### ISSUE TITLE
FUNCTION_TARGET variable is not set by --target

### ISSUE THREAD

**Issue by dinvlad** [GoogleCloudPlatform/functions-framework-nodejs#129]
Hi folks,

I tried using the framework to test the following function locally:
```es
exports[process.env.FUNCTION_TARGET] = (_, res) => {
  res.send(200);
};
```
using the default `start` script:
```json
"scripts": {
  "start": "functions-framework --target=helloWorld"
}
```
However, `npm start` fails with:
```
Function 'helloWorld' is not defined in the provided module.
Did you specify the correct target function to execute?
Could not load the function, shutting down.
```
On the other hand, if I use the script
```json
"scripts": {
  "start": "FUNCTION_TARGET=helloWorld functions-framework"
}
```
then the function starts up and works correctly.

The reason why I'm using `process.env.FUNCTION_TARGET` instead of a literal `helloWorld` name is that in a real-world scenario, I'm deploying functions under non-trivial names and I don't want a change in function name/entrypoint to suddenly break my code (so I only set entrypoint in my deployment template, and everything from there is automatic).

Would it be possible to set `FUNCTION_TARGET` using the `--target` argument instead, to be consistent with the Cloud Functions runtime (where  `FUNCTION_TARGET` variable IS indeed set, at least for Node.js 10 runtime)?

Thanks

**Comment by grant** [comment]
Hi @dinvlad,
Thank you for this issue. In the Cloud Functions runtime we don't use command-line flags like `--target`. In fact, we thought of removing this functionality (flags) to make things simpler.

However, the issue we're running into here is a little unrelated:

Re:

```js
exports[process.env.FUNCTION_TARGET] = (_, res) => {
  res.send(200);
};
```

The code sample here will not work as we don't have an environment variable when you run `npm start`. As a result, I think either the code sample should be changed or we should add the env var.

---

> Would it be possible to set `FUNCTION_TARGET` using the `--target` argument instead, to be consistent with the Cloud Functions runtime (where `FUNCTION_TARGET` variable IS indeed set, at least for Node.js 10 runtime)?

The framework aims to not modify any environment variables. So, it wouldn't make sense to set environment variables if they're not set up by the user.

Hope that makes sense. Let me know what you think.

**Comment by dinvlad** [comment]
Thanks - I'm coming more from the perspective of "use Functions Framework to emulate the real Cloud Functions runtime as close as possible".

Since the Cloud Functions runtime for Node.js 10+ does set that variable (https://cloud.google.com/functions/docs/env-var#nodejs_10_and_subsequent_runtimes), then it would seem we should also set it automatically in the Functions framework. Otherwise, we get deviating behavior where the users _may_ use the documented variable in the real Cloud Functions, but it doesn't work when running locally.

Does that sound reasonable?

**Comment by grant** [comment]
So for the question of emulating Google Cloud Functions as much as possible, the part that is missing is the set of environment variables added to your custom set of environment variables when building the container deployed to Google container infra. 

Basically a GCF function = Your code + FF + buildpack where the buildpack is a Dockerfile with some environment variables.

The command-line support for this Functions Framework is never used by GCF.

**Comment by dinvlad** [comment]
OK, I see - that seems reasonable. I guess we can always set those "general" vars "manually", in addition to the custom ones.

That being said, I think `FUNCTION_TARGET`, `FUNCTION_SIGNATURE_TYPE` and `PORT` _are_ always known to FF, since they correspond to `--target`, `--signature-type`, and `--port` args to FF.

Could we perhaps at least set these (unless they're set explicitly by the user), and then if the user really needs to, they can manually set `K_SERVICE` and `K_REVISION` (in some limited cases where those are used by the user code).

**Comment by grant** [comment]
So, the buildpack sets the environment variables for the user-provideable vars if not given. It's a layer that uses the Functions Framework.

We don't expect the Function Frameworks in every language to set these env vars if not set. That would be extra coding in all 7 language repos. Rather we have the buildpack set any missing configs with a build script.

**Comment by dinvlad** [comment]
OK, I see - thanks for the explanation!
