### ISSUE TITLE
Cloud Function in Typescript

### ISSUE THREAD

**Issue by paulwoelfelcpl** [GoogleCloudPlatform/functions-framework-nodejs#13]
The functions framework expect a index.js in the local directory. I'm writing my functions in Typescript and test it locally with nodemon, ts-node and a ts file, which starts the express server. 

Is there a better way than running `tsc` every time something changes and then start the functions-framework?

**Comment by paulwoelfelcpl** [comment]
My solution right now is to use [tsc-watch](https://www.npmjs.com/package/tsc-watch) and the following command:

```bash
npx tsc-watch --onSuccess 'npx @google-cloud/functions-framework --function-target=main --port=8080 --function-signature-type=http'
```

In the local directory I created `index.js`, which loads the transpiled js:

```javascript
const cloudFunctions = require("./dist");

Object.keys(cloudFunctions).forEach(
  key => (exports[key] = cloudFunctions[key])
);

```

And that's the `tsconfig.json`

```json
{
  "compilerOptions": {
    "outDir": "./dist",
    "target": "es2018",
    "lib": ["dom", "es2018"],
    "module": "commonjs",
    "esModuleInterop": true,
    "pretty": true,
    "sourceMap": true
  },
  "include": ["./src/**/*"],
  "exclude": ["node_modules"]
}
```

**Comment by stew-r** [comment]
Hey there -- I think your solution is a good one. The framework should work with standard JS tooling so I'm glad you were able to make this work.

**Comment by QuantumInformation** [comment]
Why do the docs say to do `npm install @google-cloud/functions-framework`

but then tell you to use npx later?

**Comment by stew-r** [comment]
They're two different tools. [See here](https://stackoverflow.com/questions/50605219/difference-between-npx-and-npm) for a more detailed explanation.

**Comment by fernandofleury** [comment]
This is how I'm achieving it using `nodemon`:

```
"start": "functions-framework --target=event",
"build": "npm run build-ts",
"watch": "concurrently -k -p \"[{name}]\" -n \"TypeScript,Node\" -c \"yellow.bold,cyan.bold,green.bold\" \"npm run watch-ts\" \"npm run watch-node\"",
"watch-node": "nodemon --watch ./build/ --exec npm run start",
```
