### ISSUE TITLE
res.render() doesn't work with bundled Express

### ISSUE THREAD

**Issue by dinvlad** [GoogleCloudPlatform/functions-framework-nodejs#130]
Hi folks,

I'd like to use a templating engine with a function deployed in functions-framework style:
```es
exports.index = (_, res) => {
  res.render("index.ejs");
};
```
I have also imported `ejs` engine in my `package.json`:
```json
  "dependencies": {
    "ejs": "^3.0.2"
  },
```
However, when I invoke the deployed function, it fails with
```
Error: Cannot find module 'ejs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at new View (/layers/google.nodejs.functions-framework/functions-framework/node_modules/express/lib/view.js:81:14)
    at Function.render (/layers/google.nodejs.functions-framework/functions-framework/node_modules/express/lib/application.js:570:12)
    at ServerResponse.render (/layers/google.nodejs.functions-framework/functions-framework/node_modules/express/lib/response.js:1012:7)
    at exports.(anonymous function) (/workspace/index.js:2:7)
    at process.nextTick (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/invoker.js:243:17)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

On the other hand, when I modify the code to construct `express` object explicitly:
```es
const express = require("express");
const app = express();

app.get("/", (_, res) => {
  res.render("index.ejs");
});

exports.index = app;
```
with
```json
  "dependencies": {
    "ejs": "^3.0.2",
    "express": "^4.17.1"
  }
```
then it works.

Since the difference in these 2 cases seems to be that the 1st approach uses Express "bundled" with the Node.js 10 runtime, it seems like `functions-framework` is unable to resolve modules imported "implicitly" by the "bundled" Express.

That being said, when I run the function created with the 1st approach locally, using `functions-framework --target=index`, it works as expected. This seems to suggest that this is more of a problem with the runtime. Could you confirm if this issue belongs here or should I possibly open a ticket with Google support/tracker?

Thanks

**Comment by hdp617** [comment]
I _think_ this is because of an optimization in production. The directory in the production environment is different from the local directory.
- Does it work if `"express"` is in `package.json` without constructing `express` object?
- Does it work if `"@google-cloud/functions-framework"` is in `package.json`?

**Comment by dinvlad** [comment]
OK, interesting!
- With `express` I get the same error.
- With `express` AND `@google-cloud/functions-framework` - same error
- With just `@google-cloud/functions-framework` - no error!

I had `@google-cloud/functions-framework` as a `devDependencies` previously, but obviously that didn't help at runtime. Now that's in `dependencies` and works!

Do you think this could be somehow improved, or will we have to keep it in `dependencies`, or perhaps `peerDependencies` (which also works)?

We wanted to avoid having it explicitly listed to avoid the additional burden of keeping the library (and its nested dependencies) up to date (which triggers security vulnerability alerts every now and then and requires additional oversight from us as secops folks).

Thanks!

**Comment by hdp617** [comment]
> Do you think this could be somehow improved, or will we have to keep it in `dependencies`

Yes, I _think_ this can be fixed. Thanks for reporting.

I'm closing this issue here because this is not an issue with the Functions Framework per se but with the runtime. Would you mind opening a ticket with Google support/tracker?

**Comment by dinvlad** [comment]
Thanks - could you share a link to the public tracker appropriate for this?

**Comment by grant** [comment]
> Thanks - could you share a link to the public tracker appropriate for this?

https://issuetracker.google.com/issues?q=status:open%20componentid:187195
