### ISSUE TITLE
Feature request: set environment using .env.yaml

### ISSUE THREAD

**Issue by gdevacc12** [GoogleCloudPlatform/functions-framework-nodejs#131]
Please would a feature be added so that the environment for the function uses .env.yaml for the environment configuration.

Perhaps a switch should be specified with the npm script so the feature mirrors the deployment option to have the variables deployed/used or not.

**Comment by grant** [comment]
Hi @gdevacc12, this question has already been asked in a different issue. TL;DR: `.env.yaml` is only used and supported with the `gcloud` tool.

https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/116
