### ISSUE TITLE
Refactor invoker.ts functionality into separate files

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/functions-framework-nodejs#134]
The `invoker.ts` file of ~600 lines contains dozens of pieces of logic that are somewhat unrelated:
- Error handling
- Serving
- Routing
- Eventing
- Logging

This makes the framework difficult to understand and introduces many "global" variables. It would be much easier to separate some of these functions out into separate files.

**Comment by hdp617** [comment]
Thanks for bringing this up Grant! I think all the logic to load user's function like `getUserFunction` can be moved to its own file as well.
