### ISSUE TITLE
Update `package-lock.json`. Configure CI to Keep Lock File Updated

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/functions-framework-nodejs#161]
It looks like our `package-lock.json` file is outdated, which caused a sizable diff (from the lock file) when installing this package. #160

Should we configure renovate or something to prevent this?

**Comment by grant** [comment]
For example, https://github.com/googleapis/google-api-nodejs-client/blob/master/renovate.json

**Comment by hdp617** [comment]
> Should we configure renovate or something to prevent this?

SGTM. I think I set up renovate a while back but I forgot to enable it. I think we can reopen this PR https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/65
