### ISSUE TITLE
[Cloud Run] Is it possible to deploy multiple services with same google container image?

### ISSUE THREAD

**Issue by manwithsteelnerves** [GoogleCloudPlatform/functions-framework-nodejs#184]
I want to create 3 services with different environment variables from the same google container image. Is it possible?
Currently i'm using functions framework to create the docker image(by adding start script to package.json).

Unfortunately, its not letting me to specify any other name for service other than the function name i used in the functions framework target.

    "start": "functions-framework --target=app --signature-type http"
In the above command, app is my exported function name.

When I deploy service name with ZZZ instead of app, it fails with below error.
```
Function 'app' is not defined in the provided module.
Did you specify the correct target function to execute?
Could not load the function, shutting down.
```

If i deploy with service name as app, it works fine.

Can someone suggest on how to solve this?

**Comment by grant** [comment]
Hi, can you use different **environment variables** per deployed service?

Then you can deploy the container once, but start the FF with different configs. Using the env var either in the npm start script or in the application's code (`process.env.`).

The setup likely depends on your `Dockerfile`.

**Comment by manwithsteelnerves** [comment]
Thanks grant.
I got it working in way you said.

I deployed single docker image to gcr.io and while deploying for cloud run, I passed FUNCTION_TARGET(set env variable) as the function that needs to be invoked as target for functions-framework.

This way I was able to create multiple services with functions framework on cloud run.

Only problem I see is the service name needs to match FUNCTION_TARGET name which is not great. Hopefully there is a valid reason for that kind of restriction. Would be great if there is some info on it.

Thanks,
Ayyappa

**Comment by hdp617** [comment]
> Only problem I see is the service name needs to match FUNCTION_TARGET name which is not great.

I don't _think_ this is a requirement. The service name (`K_SERVICE` env var) does not need to match the function to be invoked (`FUNCTION_TARGET` env var).

**Comment by manwithsteelnerves** [comment]
@hdp617 I keep getting the error that the function is not found if there is a mismatch.

**Comment by hdp617** [comment]
I tested with a container image built from [0] and deployed multiple services with different function targets and I didn't run into that issue. Could you share the error message and the repro steps?

[0] https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/functions/helloworld/index.js

**Comment by grant** [comment]
Hey, I'm going to close this issue as I think it's resolved from the comments above and due to inactivity. Please re-open with specific reproduction issues if there's still a problem.
