### ISSUE TITLE
README says --target instead of --function-target

### ISSUE THREAD

**Issue by anishkny** [GoogleCloudPlatform/functions-framework-nodejs#19]
Following the README (master on github) locally causes an error:

```
$ npx @google-cloud/functions-framework --target=helloWorld
Function 'function' is not defined in the provided module.
Did you specify the correct target function to execute?
Could not load the function, shutting down.
```

**Comment by stew-r** [comment]
Thanks for reporting this. We need to cut the v1.1.0 npm package to make the package reflect the current (intended) state of the docs.

You can temporarily use `npx @google-cloud/functions-framework --function-target=helloWorld`. We're transitioning to the shorter `npx @google-cloud/functions-framework --target=helloWorld` in 1.1.0.

**Comment by swalkowski** [comment]
@google-cloud/functions-framework version 1.1.0 has been [published to npm](https://www.npmjs.com/package/@google-cloud/functions-framework/v/1.1.0), `npx @google-cloud/functions-framework --target=helloWorld` works well now.

Thanks again for your report!
