### ISSUE TITLE
Expose trace IDs in background and cloud event functions

### ISSUE THREAD

**Issue by juliehockett** [GoogleCloudPlatform/functions-framework-nodejs#197]
The `X-Cloud-Trace-Context` header is included in requests, but as we don't expose headers to the event-style functions it is inaccessible. This value is the only means of grouping StackDriver logs by request, and so we should expose it to the user function code.

Background events: The trace ID should be available in the `context` parameter.

CloudEvents: The trace ID should be encoded as an extension on the event, leveraging the `traceparent` extension field as described in https://github.com/cloudevents/spec/blob/master/extensions/distributed-tracing.md.

**Comment by grant** [comment]
https://github.com/googleapis/google-cloudevents/issues/39#issuecomment-670781961
