### ISSUE TITLE
Example of a Cloud Storage event

### ISSUE THREAD

**Issue by jeff-got** [GoogleCloudPlatform/functions-framework-nodejs#203]
I am building a cloud function that will be using the Cloud Storage update event. I am trying to test this locally with the Enable Google Cloud Functions Events example by passing a csv file to the function to test.

I am unable to find any examples of of a Cloud Storage event payload that is need. I have tried working through the Pub/Subs examples but these take JSON messages. I can't find how to pass the actual file. When i do the POST the data comes as undefined

**Comment by grant** [comment]
Does this doc help?
https://cloud.google.com/functions/docs/testing/test-background

We should have examples here:
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/functions/helloworld

CC @ace-n

**Comment by jeff-got** [comment]
Hi Grant,
Thanks for the response but unfortunately not.
I am trying to build a function that does some thing like [this](https://medium.com/google-cloud/a-cloud-function-to-automate-google-spreadsheet-csv-import-d2ffb8fbe9b4) but goes to a MySQL database instead.
These examples plus the others show the sending of the HTTP request, what i am unable to find is how to pass the actual CSV file to the function or set it up so that it can look at a simulated bucket to retrieve the file like [these](https://cloud.google.com/sdk/gcloud/reference/beta/emulators) emulators

**Comment by ace-n** [comment]
You should be able to pass in a filepath on your local system to your function, and confirm that it is processed as intended.

You could _also_ host the file in a test Cloud Storage bucket, and pass that path in too (perhaps as an environment variable or hard-coded constant).

(Storage-triggered Cloud Functions themselves **do not** accept file _contents_, so you'd have to [call the GCS API](https://cloud.google.com/storage/docs/downloading-objects#code-samples) to get the actual contents of a file.)

**Comment by jeff-got** [comment]
Great thank you. 
I should be able to check and see if the function is running locally and add the path to read the file or use the bucket if running from Cloud Functions.
