### ISSUE TITLE
Unable to remove response header

### ISSUE THREAD

**Issue by SDrinkwater** [GoogleCloudPlatform/functions-framework-nodejs#206]
There doesn't seem to be a way to remove a response header. I am trying to remove the X-Powered-By header. I am only able to set its value, through which I can effectively achieve the same result, but it would be nice to be able to actually remove the header.

Is there some way to achieve this?

Issue originally raised here: https://github.com/firebase/firebase-functions/issues/754

**Comment by grant** [comment]
Hi @SDrinkwater,
Sorry, I don't understand your question. With `res.send(` in Express, you can send any response.

https://expressjs.com/en/api.html#res.send

The `X-Powered-By` is not coming from this library.

**Comment by rhodgkins** [comment]
I'd also like to see this functionality added as we are also trying to remove the `x-powered-by` header.

@grant I think this header is coming from this library as it creates the express app:

https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/5d61008f7855cfc10877f6bf580eaef2487a4ca8/src/invoker.ts#L349

The default setting for `x-powered-by` is `true` which means the value of the header will be `express` ([see the docs](https://expressjs.com/en/api.html#app.settings.table)).

Then any sub-apps that are used for client function routes have their `x-powered-by` setting ignore.

You can try it with the following:

```js
const app = express()
app.get('/', (req, res) => {
   res.send('Will have x-powered-by header')
})    

const subapp = express()
subapp.disable('x-powered-by')
subapp.all('*', (req, res) => {
   res.send(`Will still have x-powered-by header despite being disabled: subapp.enabled('x-powered-by')=${subapp.enabled('x-powered-by')}`)
})
app.use('/subapp', subapp)

// Matches how functions are called
app.all('/calledsubapp', (req, res, next) => {
   subapp(req, res, next)
})
```

Querying the main app:
```
curl -i http://localhost:3000       
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Content-Length: 29
ETag: W/"1d-6q73dA/19m+t4qsFOySdg9LHLZI"
Date: Tue, 15 Sep 2020 08:09:26 GMT
Connection: keep-alive

Will have x-powered-by header     
```

Querying the sub app:
```
curl -i http://localhost:3000/subapp
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Content-Length: 96
ETag: W/"60-FbpOzXvracH4MnF2RPc157pCkPE"
Date: Tue, 15 Sep 2020 08:10:35 GMT
Connection: keep-alive

Will still have x-powered-by header despite being disabled: subapp.enabled('x-powered-by')=false
```

Querying the called sub app:
```
curl -i http://localhost:3000/calledsubapp
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Content-Length: 96
ETag: W/"60-FbpOzXvracH4MnF2RPc157pCkPE"
Date: Tue, 15 Sep 2020 08:17:51 GMT
Connection: keep-alive

Will still have x-powered-by header despite being disabled: subapp.enabled('x-powered-by')=false
```

Adding in `app.disable('x-powered-by')` removes the header for all three cases.

Also [the docs even explicitly recommend](https://expressjs.com/en/advanced/best-practice-security.html#at-a-minimum-disable-x-powered-by-header) disabling this header.

**Comment by rhodgkins** [comment]
Happy to do a PR (with some tests) to at least disable the `x-powered-by` header...

**Comment by grant** [comment]
Oh, I don't think this header is intentionally added.

A PR with tests to disable the header for all functions would be great. @rhodgkins

**Comment by grant** [comment]
Hi folks,
Above or here is a sample where you can use helmet.
https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/214#issuecomment-693523420

LMK if there are other issues with removing that response header.

**Comment by rhodgkins** [comment]
This issue should be closed or at least another issue about `x-powered-by` should be opened. 

Even using helmet my above reproduction steps still apply for that header as it’s being set at a level where the end function user can’t reach.

**Comment by SDrinkwater** [comment]
@grant Can we please reopen this issue. The comment you linked https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/214#issuecomment-693523420 doesn't solve the problem, it just suggests why helmet shouldn't be installed by default.

The problem really comes down the fact that we don't have access to the root `app` so are unable to override settings on it.

**Comment by grant** [comment]
Sure, I can re-open.

Did exporting an express app with helmet middleware not solve the issue? That should intercept all requests and is essentially the root app (the root app routes all requests to your app). And `app.disable('x-powered-by');` should disable the header.

Can you provide reproduction steps and expected/actual behavior you are seeing with code?

**Comment by SDrinkwater** [comment]
@grant  Alright, looks like I might have jumped the gun. Adding helmet to an express function does remove the header, as does the following code:

```js
const app = express();
app.use((_req, res, next) => {
  res.removeHeader("X-Powered-By");
  next();
});
app.use(testFunction);

function testFunction(req, res) {
  res.send("Hello World");
}

exports.testFunction = app;
```

However, I originally raised this issue as a suggestion from another very similar issue raised in the `firebase/firebase-functions` repo https://github.com/firebase/firebase-functions/issues/754.

This library is apparently the underlying framework used by firebase cloud functions and hence the question posted here.

Using the above technique doesn't remove the header when used with firebase-functions `https.onRequest`, so there has to be some kind of handling in between somewhere. Happy to take the problem back to that other repo, unless there is some way you can coordinate with them?

**Comment by grant** [comment]
Thanks for working through this.

If the only ask is to remove the header, I think adding a line to remove it wouldn't be contested: 

```ts
app.set('x-powered-by', false);  
```

Here:

https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/63cb628f580bc398924dd38e618498db36c76c82/src/server.ts#L87

I think there was some contention with adding `helmet`, but just removing that header should be fine.

<details>
  <summary>Previous thoughts</summary>
  
I don't mean to juggle the issue, but if there is a way in this repo/module to remove the header, but a consumer (Firebase Functions) doesn't support this solution, that sounds like it should be triaged with Firebase Functions.

The Functions Framework supports Express middleware so you can `export const app = <express object>`. So using helmet or just the [direct middleware](https://github.com/helmetjs/helmet/blob/a51585360c896f2b52ab0d2ed84a8d94d7e41c24/middlewares/x-powered-by/index.ts#L3) should work.

In the PR, we talked about adding Helmet, but we're sure if we wanted to add every feature and if all users wanted that https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/214#issuecomment-693523420.

</details>
