### ISSUE TITLE
CloudFunctionsContext no longer exported?

### ISSUE THREAD

**Issue by techieshark** [GoogleCloudPlatform/functions-framework-nodejs#216]
I had working code as below on functions-framework@1.4.0:

```
import { CloudFunctionsContext } from '@google-cloud/functions-framework';
import { Message } from '@google-cloud/pubsub';

/**
 * A cloud function triggered by a PubSub message.
 * @see https://cloud.google.com/functions/docs/writing/background#function_parameters
 */
exports.pubsub = async function pubsub(
  pubsubMessage: Message,
  context: CloudFunctionsContext
) {
...
```

after updating to latest (1.7.1), I got TS error on first line:
```
Module '"../node_modules/@google-cloud/functions-framework/build/src/invoker"' has no exported member 'CloudFunctionsContext'.ts(2305)
```

I resolved this by changing the line to
```
import { CloudFunctionsContext } from '@google-cloud/functions-framework/build/src/functions';
```

but it suggests a couple questions:

1) Was I (and am I know) using the types as intended, and
2) Was this an intentional change (I did see some refactors mentioned in the release log), or should `CloudFunctionsContext` still be exported from the top level?

Thanks!

**Comment by grant** [comment]
Hey @techieshark,
Sorry for changing the location of the interfaces. I should have mentioned the breaking change if folks are using the interfaces in the changelog.

It looks like you caught a bug!

The interfaces are here:
https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/package.json#L10

But we moved the interfaces in this file:

They should point to here:
https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/src/functions.ts

---

We should:
- Change the package.json
- Document the TS interfaces in the README

What do you think?
