### ISSUE TITLE
process.on('exit', ... always errors

### ISSUE THREAD

**Issue by anishkny** [GoogleCloudPlatform/functions-framework-nodejs#22]
Doesn't the following line mean that the process will always end in an error?

https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/518f2d0b4f171273dc9e7e724f6a3ffdc90db8d9/src/invoker.ts#L531

What is the non-error-producing recommended way to stop the server? Say after testing in a CI environment?

**Comment by grant** [comment]
That's a good question.
I don't think there is a great way to stop the server now without an error.

Do you have a recommendation for what could fix this? Simply removing the error?

**Comment by grant** [comment]
I think we'd need to change the hander to return `0` and not call `logAndSendError`.

**Comment by anishkny** [comment]
Hey sorry had forgotten about this. Something like this would be very useful:

```
npx @google-cloud/functions-framework --run-script "./test-my-api.sh"
```

This should spin up the API and then run `test-my-api.sh` (or whatever) and when the script is done, quit the API and marshal back the exit code for CI.

**Comment by chrisLeeTW** [comment]
@grant I thinks this is very good and simple and elegant solutions for this problem.

**Comment by grant** [comment]
This should be fixed now on `master` with https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/187.
