### ISSUE TITLE
Support ESM

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/functions-framework-nodejs#233]
Right now this module doesn't support ESM. If you try to use modules, your function will not load.

```
Provided module can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/timmerman/Documents/trash/esmtestff/index.js
require() of ES modules is not supported.
```

I believe there are a few things we need to do to allow functions using modules to be supported:

### Allow modules in `package.json`

```json
 "type": "module",
```

### Use ESM import/export

```js
/**
 * Send "Hello, World!"
 * @param req https://expressjs.com/en/api.html#req
 * @param res https://expressjs.com/en/api.html#res
 */
export const helloWorld = (req, res) => {
  res.send('Hello, World!');
};
```

Observe error:

```
Provided module can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: esmtestff/index.js
require() of ES modules is not supported.
```

### Solution

Here's the rough solution I think, after prototyping a bit:

- `loader.js#getUserFunction`:
  - Await `const functionModulePath = await getFunctionModulePath(codeLocation);`
  - `loader.js#getFunctionModulePath`
    - We need to determine if the user code is a module or cjs.
      - if module, `await import(codeLocation)`; where `codeLocation is full file (including index.js part)`.
      - else, `require.resolve(codeLocation)`, normal require
- `index.js`: We need to async/await `getUserFunction`:
  - https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/src/index.ts#L99-L104

CC: @bcoe

**Comment by bcoe** [comment]
@grant it's possible to build a dual-mode module, I just finished doing this for [yargs-parser](https://github.com/yargs/yargs-parser).

This might be worth thinking about for the functions framework.

**Comment by grant** [comment]
Alright. So I have a prototype with what I think would work:

`bar.js`

```js
const USER_FUNCTION = 'myFunc'
const USER_FILE = './foo.js'

async function run() {
  const myFile = await import(USER_FILE);

  const res = myFile[USER_FUNCTION]();
  console.log(res);
}
run();
```

`foo.js`

```js
export const myFunc = () => 3;
```

```json
{
  "name": "dynamic-import",
  "main": "index.js",
  "type": "module",
  "scripts": {
    "start": "node ."
  }
}
```

You got to be pretty careful with how you load your file.

**Comment by mesqueeb** [comment]
@grant isn't `"exports"` Better than `"main"` in package.json for esm?

**Comment by grant** [comment]
> @grant isn't `"exports"` Better than `"main"` in package.json for esm?

I don't think the FF user needs to provide module exports like that. Maybe provide an example if you think so?

This case is very different than most modules that support ESM. The FF loads the user's code which can be a ESM, we don't use the FF itself as a module/library (it's a binary).

**Comment by mbleigh** [comment]
Hey folks, just wanted to provide a nudge and a backlink to https://github.com/firebase/firebase-tools/issues/2994 -- on the Firebase side we have 50+ developers 👍  requesting ESM support. We can't add it for Firebase until it gets added for FF, so if it's possible to make progress that would be great for our users!

**Comment by bcoe** [comment]
@mbleigh @grant the approach of using dyamic imports seems pretty smart, perhaps we could start with this being something that users opt into, with a slightly modified `start` script?

Test with the folks who are excited for this feature in `firebase`, then at some point in the future, make it the default behavior?

**Comment by neilstuartcraig** [comment]
Just adding my +1 to this as it's currently preventing me using ES modules in Cloud Functions (not firebase).
I'd be happy to contribute if that's useful.

**Comment by koistya** [comment]
This feature stopped working today (or, yesterday):
```
To load an ES module, set "type": "module" in the package.
```

**Comment by arcinston** [comment]
This still isnt working for me any working solution to fix this?

**Comment by matthewrobertson** [comment]
@[arcinston](https://github.com/arcinston) this feature should be working. Please open a new bug describing your project configuration if you are having issues.
