### ISSUE TITLE
hot reload

### ISSUE THREAD

**Issue by ptone** [GoogleCloudPlatform/functions-framework-nodejs#24]
add src watch and hot-reload (including typscript transpile) for local serving

**Comment by stew-r** [comment]
Is the request to add this to the Functions Framework `package.json`? What would be the benefit/downside of doing this for all users of the Functions Framework vs. having a user add it to their own `package.json`?

**Comment by ptone** [comment]
The devux for iterating on function development locally is currently:

1. write index.js
2. npm start
3. hit localhost:8080
4. edit index.js  "hello world" -> "hello brave new world"; save
5. reload  localhost:8080:  see only "hello world"
6. Ctr-C the local server
7. restart with npm start

Repeat for each edit of index.js

There are probably several ways to solve it, and I would defer to greater npm experts

    "start": "functions-framework --target=helloWorld"
checks for an env var such as FF_RELOAD and implements the live behavior

or use a different npm script

    "develop": "functions-framework --target=helloWorld --reload"


See also: https://www.npmjs.com/package/live-server

**Comment by stew-r** [comment]
Yeah, I acknowledge the value of live/hot reloading your code. But isn't that something you would add to your `package.json` rather than integrating it directly into the framework? Do all users want to take a dependency on a package like `live-server`?

**Comment by ptone** [comment]
I see your point about dependency bloat, what if I work up some readme content or docs on how to include https://www.npmjs.com/package/npm-watch usage, that seems to be the best fit (just did a basic test, and it WAI.  I also might just prototype it, or roll it into https://github.com/ptone/node-cloud-function-boiler

**Comment by grant** [comment]
We could add a quick tutorial on how to set up hot reloading. It's a much better developer experience than starting and stopping the server over and over.

`package.json`

```json
{
  "name": "ffreload",
  "main": "index.js",
  "dependencies": {
    "@google-cloud/functions-framework": "^1.1.0"
  },
  "watch": {
    "start": "*.js"
  },
  "devDependencies": {
    "npm-watch": "^0.6.0"
  },
  "scripts": {
    "watch": "npm-watch start",
    "start": "npx @google-cloud/functions-framework --target=helloWorld"
  }
}
```

`index.js`
```js
exports.helloWorld = (req, res) => {
  res.send('Edit me...');
};
```

Server:
`http://localhost:8080`

Logs:
```sh
npm run watch

> ffreload@1.0.0 watch /Documents/trash/ffreload
> npm-watch

No task specified. Will go through all possible tasks
[start] [nodemon] 1.18.11
[start] Serving function...
[start] Function: helloWorld
[start] URL: http://localhost:8080/
[start] [nodemon] restarting due to changes...
[start] [nodemon] starting `npm run -s start`
[start] Serving function...
[start] Function: helloWorld
[start] URL: http://localhost:8080/
[start] [nodemon] restarting due to changes...
[start] [nodemon] starting `npm run -s start`
[start] Serving function...
Function: helloWorld
```

**Comment by ptone** [comment]
Yeah - the snippet Grant proposed is exactly what I was suggesting by some readme snippet and is a great place to start.  I ended up using a different watch tool (tsc-watch) for my boilerplate example, and it works quite well: https://www.youtube.com/watch?v=ncK3zRPYQpM&feature=youtu.be

**Comment by stew-r** [comment]
I'm going to close this as your and grant's comments clearly show how to incorporate hot reload. I don't think we should document using standard Node.js tooling on the README for the Functions Framework. But maybe a blog post would be a good way to convey this information?

**Comment by narizwallace** [comment]
In case someone is looking for `debug` experience something like this can give you what you need:

```
{
  "name": "ffreload",
  "main": "index.js",
  "dependencies": {
    "@google-cloud/functions-framework": "^1.1.0"
  },
  "watch": {
    "startWatch": "*.js",
    "inspectWatch": "*.js",
  },
  "devDependencies": {
    "npm-watch": "^0.6.0"
  },
  "scripts": {
    "start": "npm-watch startWatch",
    "inspect": "npm-watch inspectWatch",
    "startWatch": "npx @google-cloud/functions-framework --target=helloWorld",
    "inspectWatch": "npx --node-arg=--inspect @google-cloud/functions-framework --target=helloWorld"
  }
}
``` 

Then you can run `npm run inspect`

**Comment by sahinerbay** [comment]
Here is my setup including babel workaround (functions-framework is pointing complied code in `/dist` folder): 

`npm i npm-run-all nodemon`

`run-s` is for running npm scripts in a sequential way

`package.json`

```
"scripts": {
    "build": "babel src --out-dir dist",
    "functions": "functions-framework --target=index --source=dist/index.js",
    "dev": "nodemon --exec run-s build functions",
  },
```

`nodemon.json` (make sure to ignore `/dist` folder)

```
{
  "watch": ["src"],
  "ignore": [".git", "node_modules/**/node_modules", "dist"],
  "delay": "3",
  "ext": "js,json"
}
```

`babel.config.js`
```
module.exports = {
  presets: ["@babel/preset-env"],
  plugins: [
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-object-rest-spread",
  ],
};
```

`/src/index/js`
```
export const index = (req, res) => {
  res.send("test");
};
```

**Comment by jonsherrard** [comment]
Nice work @grant and @narizwallace! Just what I was looking for, thanks for taking the time!

**Comment by wcoder** [comment]
**UPDATE**

The accepted answer is not working when you also want to inspect/debug the function with hot reload.

**Solution:**

You can just use and configure [nodemon](https://www.npmjs.com/package/nodemon) directly without additional wrapper packages:

`package.json`

```json
{
  "name": "debug-with-reload",
  "main": "index.js",
  "dependencies": {
    "@google-cloud/functions-framework": "^3.3.0"
  },
  "devDependencies": {
	"nodemon": "^3.0.3"
  },
  "scripts": {
    "debug": "nodemon --inspect node_modules/.bin/functions-framework --target= helloWorld"
  }
}
```

`index.js`

```js
exports.helloWorld = (req, res) => {
  res.send('Edit me...');
};
```

Server:

http://localhost:8080/

**Comment by manh-gntvn** [comment]
Hi, i use https://github.com/privatenumber/tsx to run the service in local development, code is written by Typescript:

File: package.json

```json5
{
  // ....
  "scripts": {
      "dev": "tsx watch node_modules/.bin/functions-framework --target=myFuncName --source=src/index.ts",
      "build": "tsc"
   }
   // ....
}
```
