### ISSUE TITLE
docs: express routing documentation

### ISSUE THREAD

**Issue by bashleigh** [GoogleCloudPlatform/functions-framework-nodejs#241]
Hey Guys! 

Getting the hang of using GCF! Really liking them! However struggled with routing for the past 2 hours 😂   I wanted to build a CRUD application so imagine 

```
POST /company 
PUT /company/:id
GET /company
GET /company/:id
```

and so on. 

I did find some examples using express however, (idiot moment here) I didn't realise the exported const name became part of the URL. 
So I've found that to achieve what I want above I need to do this 

```ts
app.post('', createCompany);
app.get('', paginateCompanyForUser);
app.get('/:id', getCompany);
app.put('/:id', updateCompany);

exports.company = functions.https.onRequest(app);
```
Becomes `/company`.

Whereas I was putting my prefix in the url `/company/:id` in the path params as I normally would do with express which became `/company/company/:id`.

Where if any, would be the best place to mention this? My eureka moment came whilst looking at the [following page](https://firebase.google.com/docs/functions/http-events#using_existing_express_apps), I don't suppose the firebase docs are the same relation to your `@google-cloud/functions-framework` package (in terms of team/responsibility)? 

This is the example I first found which I followed https://medium.com/google-cloud/express-routing-with-google-cloud-functions-36fb55885c68
Perhaps updating this will prevent others from experiencing my misery!

I also, don't mind adding this to your docs folder in this repo if you'd like me to?

**Comment by grant** [comment]
Hey @bashleigh,

Thanks for the issue.

For building a CRUD application, I would recommend Cloud Run. Cloud Functions is really meant for building serverless functions with one route – one function. The platform and resulting URL path from Functions is not ideal for CRUD apps.

As a result, we don't directly recommend this in a doc, but a concrete suggestion is recommended.

I'm glad the blogpost helps.

I think you might be using Firebase Functions (it does use this module) – which might mean the request is best suited for https://github.com/firebase/functions-samples.

**Comment by grant** [comment]
Hope the above comment makes sense.

For the above reason, we're not documenting this side-effect of the Functions Framework. Please comment here if you'd like me to re-open this issue for a reason. Thanks!

**Comment by ggorlen** [comment]
> ```ts
> exports.company = functions.https.onRequest(app);
> ```

Using only `exports.company = app;` was sufficient for me.
