### ISSUE TITLE
Implement CloudEvent to Event

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/functions-framework-nodejs#253]
- Pub/Sub CE to event

Look at this PR:

https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/237

**Comment by grant** [comment]
Probably fixed with https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/283 @matthewrobertson

**Comment by matthewrobertson** [comment]
I will close this once we cut a release an update the default npm package version in our buildpacks.
