### ISSUE TITLE
Missing package.json fields, warnings like "npm WARN functions-framework@ No description"

### ISSUE THREAD

**Issue by techieshark** [GoogleCloudPlatform/functions-framework-nodejs#257]
I'm looking at the cloud build logs while debugging a failed `gcloud functions deploy`. I came across these warnings, which I am certain have nothing to do with the issue I'm investigating, but in any case it'd be nice to get distracted by functions framework warnings. 

Possible to update these missing fields (license, description, repo etc)?

![image](https://user-images.githubusercontent.com/1072292/109725026-a4b57180-7c04-11eb-8423-54afa44cc055.png)

Calling attention to these specific lines:
```
npm WARN functions-framework@ No license field.
npm WARN functions-framework@ No repository field.
npm WARN functions-framework@ No description
```

**Comment by grant** [comment]
Hi,
I don't know exactly where these logs are coming from.
The package is not `functions-framework@`. The package is `@google-cloud/functions-framework`. Maybe that is your code? Can you share your code?

We have these fields in the framework here:
https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/package.json

**Comment by grant** [comment]
It might be an issue in the buildpack.

**Comment by grant** [comment]
Maybe from here:

https://github.com/GoogleCloudPlatform/buildpacks/blob/97bbe235d46ed21e5ce56a40d09f82f1560070a0/cmd/nodejs/functions_framework/main.go#L32

**Comment by techieshark** [comment]
> Maybe that is your code? Can you share your code?

Hi @grant, I sent an email to the gmail address I found on your website. I hope that helps.

Thanks!

**Comment by grant** [comment]
I'm not sure if this issue has been triaged or is related to this other issue:

https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/258#issuecomment-791850281

I can't personally debug issues like this via email. It seems like things are alright and there are no immediate issues from this npm module. As such, closing.

If there's still an issue with this module, please provide exact minimal repro steps here. Thanks!
