### ISSUE TITLE
Problem with ending of process when developing locally

### ISSUE THREAD

**Issue by alexbchr** [GoogleCloudPlatform/functions-framework-nodejs#260]
I use `yarn functions-framework --target=handler` to test a simple function returning a fooBar text. 

## The Problem
Everything works fine with `functions-framework` to test the function. However, as soon as I try to shut down the process using `CTRL+C` in my terminal (using ZSH and VS Code), I get the following error: 

```
Received SIGINT
```

If I try to end the process multiple times, I get this same error again and again. After some time (like a minute or two), the process ends by itself.

## Expected Behavior

The process should end as soon as I `CTRL+C`, without any SIGINT error.

UPDATE: [The comment here](https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/126#issuecomment-638220477) seems to describe the exact same issue

**Comment by grant** [comment]
Thanks. I have noticed this too. We can investigate improving this experience.
