### ISSUE TITLE
typescript deployment error

### ISSUE THREAD

**Issue by CorneilleEdi** [GoogleCloudPlatform/functions-framework-nodejs#288]
I've been having some errors while deploying my typescript cloud function (the sample in the documentation).

`npm run compile` fails because `tsc: not found`.
If I move `typescript` from a dev dependency to a dependency then `Cannot read file '/workspace/node_modules/gts/tsconfig-google.json'`.

I think that the errors are happening because the dev dependencies are not being installed (the normal approach).
I can't just move all dev dependencies to dependencies. 

What is the best way to resolve it?

**Comment by grant** [comment]
Hi there, I can't seem to reproduce the problem.

I tried the typescript tutorial and it seemed to work as expected.

You might want to look at this thread:

https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/254#issuecomment-828154320

**Comment by grant** [comment]
Do you have more details @CorneilleEdi ? A sample file to reproduce this problem?

**Comment by CorneilleEdi** [comment]
No more comment. Your first comment was very helpful.
Thanks

(Sorry for the delay)
