### ISSUE TITLE
How to port functions

### ISSUE THREAD

**Issue by josephburnett** [GoogleCloudPlatform/functions-framework-nodejs#29]
I had heard about the Functions Framework as a way to run the same code in many Google environments (Function, Cloud Run, Cloud Run on GKE).  I was expecting a quick-start style guide in [README.md](https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/README.md).

The README did have a quick start for running FF locally.  However when I reached the [Run your function on serverless platforms](https://github.com/GoogleCloudPlatform/functions-framework-nodejs#run-your-function-on-serverless-platforms) section, I had to visit several other pages to find the relevant commands.

Google Cloud Functions was relatively easy.  I am familiar with GCF so I knew to skip the `git pull` section and use use the [Deploy a function](https://cloud.google.com/functions/docs/quickstart#deploy_a_function) instructions.

The Google Cloud Run instructions were not so easy.  The hello world application doesn't look the same.  And I had to use two of the sections, [Containerizing an app and uploading it to Container Registry](https://cloud.google.com/run/docs/quickstarts/build-and-deploy#containerizing) and [Deploying to Cloud Run](https://cloud.google.com/run/docs/quickstarts/build-and-deploy#deploying_to).  As well as create a new file (`Dockerfile`).

The Google Cloud Run on GKE instructions only included UI instructions for [Deploying a sample container](https://cloud.google.com/run/docs/quickstarts/prebuilt-deploy-gke#deploying_a_sample_container).  I had to find the `gcloud` instructions myself (hint: change `--region` to `--cluster` and `--cluster-location`).

The value proposition of the Functions Framework is to write portable node.js code.  Functionally it succeeds.  But from a documentation standpoint it falls short.  In order to port the same node.js code to 4 environments (localhost, GCF, GCR, GCR-on-GKE) I must read 4 sets of instructions.  Which have 4 different helloworld functions.

It looks like the helloworld from FF is **not** portable (it really is).

**Comment by josephburnett** [comment]
FYI: Here is what in-lining the instructions would look like: https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/28

**Comment by QuantumInformation** [comment]
I wonder why Google deprecated so many repos, that are still in their live docs. Yes this is the only supported way now.

**Comment by stew-r** [comment]
@josephburnett 100% agree that the portability story needs to get stronger. Towards that end, we're planning to work on:
1) buildpacks that allow you to build a container without writing a Dockerfile
2) fixing event handling logic that is currently in a different part of our infrastructure

Regarding docs -- we're trying to minimize the amount of docs that need to be created and maintained by referencing existing docs (or blog posts/articles if they exist). Agreed that a single in-depth tutorial doc would be helpful. We just don't have the bandwidth to write and maintain them (especially given that we aren't getting huge customer demand for this use case yet).

**Comment by QuantumInformation** [comment]
I'm planning to make some youtube videos to complement your docs, but I just need to get over my teething issues.

**Comment by stew-r** [comment]
🚀

**Comment by grant** [comment]
For this GitHub issue, I'm not sure what the exact issue is. I have a few blogposts that show how it's not hard to simply create an Express application using this Functions Framework.

In my case, I've used the Functions Framework with:
- Google Sheets
- Localhost
- Google Cloud Functions
- Google Cloud Run

Here's an example of a portability blogpost:
https://medium.com/google-cloud/node-12-functions-on-cloud-run-d891dd93c7c8

There are some 1-time setup instructions for each environment, but you'll be using the same code once you get that set up.

I'm going to close this issue as infeasible. Let me know if there's something more we should add to the docs with specific requested changes, and we can re-open this issue.
