### ISSUE TITLE
Support for env vars

### ISSUE THREAD

**Issue by Wazbat** [GoogleCloudPlatform/functions-framework-nodejs#296]
I'd really really like it if it was possible to set env vars in a similar way to the deploy commands

For example, being able to run:

`functions-framework --target=myFunction --env-vars-file=./.env.yaml"`

Would cause the file to be read and the values be set as env variables, just like when a function is deployed. Via both `--env-vars-file` and `--set-env-vars`

**Comment by grant** [comment]
Hi! This discussion may be useful: https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/38#issuecomment-599597555

> Here is my set up to use my yaml env definitions for cloud functions cli with functions-framework:
> 
> `"start": "yaml2json env.foo.yaml >.env.json &&  env-cmd -r ./.env.json functions-framework --target=targeFunc",
> "deploy": "gcloud functions deploy myFunction --entry-point targeFunc  --env-vars-file ./env.foo.yaml "`

**Comment by grant** [comment]
We're likely not going to support YAML env vars in this package, so I'm going to close. LMK if using the library for parsing yaml env vars doesn't work.
