### ISSUE TITLE
Deployment of function for TS failure

### ISSUE THREAD

**Issue by jgunnink** [GoogleCloudPlatform/functions-framework-nodejs#303]
Hello,

I believe I've discovered a bug which I've been able to reproduce consistently I felt worth reporting.

## Summary
When using Typescript to build and deploy a function, if the target dir/file is in the gitignore, then the deployment fails.

## Description
Following on from #254, I found the issue as a similar error occurred to me:
```
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Build failed: dist/index.js does not exist; Error ID: 9e84f54e
```
As it turns out, when I have the file in my .gitignore, the command fails:
```
gcloud functions deploy notify-github --runtime nodejs14 --trigger-http --region australia-southeast1
```

However, removing `dist/` from my .gitignore file and re-running the same command works fine.

Sample code from https://github.com/golergka/gcf-typescript-template can be copy/pasted to replicate.

Originally discovered with:
```
Google Cloud SDK 339.0.0
bq 2.0.67
core 2021.04.30
gsutil 4.61
```

I noticed my tooling was a bit out of date, so I have updated just to make sure, but it was to no effect:
```
Google Cloud SDK 346.0.0
bq 2.0.69
core 2021.06.18
gsutil 4.63
```

**Comment by grant** [comment]
Hi, I think that makes sense. At some point you need to build your TS project. If you don't build or ignored a prebuilt repo, your function will not exist.

There's some conversation here:

https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/254#issuecomment-828154320

**Comment by jgunnink** [comment]
Hey thanks for the reply @grant - the compiled JS file already exists, but simply removing the line from the .gitignore seems to enable it to deploy properly.

I had a good read of that thread #254 before posting (which I also referred to in the original post).

**Comment by grant** [comment]
Cool cool. Is there anything I can do before closing the issue then?

**Comment by jgunnink** [comment]
Well I mean its up to you guys how you wanna handle bug reports, but I feel this issue is separate to the issues in #254. I personally wouldn't have thought that keeping the compiled output in the committed history of a git repo is a worthwhile thing to do, but if it works...

**Comment by grant** [comment]
Have you tried creating a separate
.gitignore
and
.gcloudignore
?

You can make sure to ignore compiled TS in git but keep JS in gcloud when deploying.

Maybe we can add more detailed instructions for this setup. If you add very detailed instructions of what doesn't work with a minimal setup, that would help me a lot to triage the issue.

**Comment by jgunnink** [comment]
Sure, in the original post I mentioned this:

> Sample code from https://github.com/golergka/gcf-typescript-template can be copy/pasted to replicate.

I will try the .gcloudignore and the .gitignore and see how that works by being more explicit. As it stands I already have the `.gitignore` entry in my `.gcloudignore` file as so:
```
# This file specifies files that are *not* uploaded to Google Cloud Platform
# using gcloud. It follows the same syntax as .gitignore, with the addition of
# "#!include" directives (which insert the entries of the given .gitignore-style
# file at that point).
#
# For more information, run:
#   $ gcloud topic gcloudignore
#
.gcloudignore
# If you would like to upload your .git directory, .gitignore file or files
# from your .gitignore file, remove the corresponding line
# below:
.git
.gitignore
node_modules
#!include:.gitignore
```
So I would have thought that ignoring the .gitignore in the gcloudignore would mean that the compiled JS is included.

**Comment by grant** [comment]
Thanks. However, I'm sorry, I don't see the exact issue from above.

> When using Typescript to build and deploy a function, if the target dir/file is in the gitignore, then the deployment fails.

That is expected. Cloud Functions is not going to compile TypeScript for you. Compiling TS and deploying should work.

Can you provide exact reproduction steps in the GitHub issue and what specifically should be changed?

**Comment by jgunnink** [comment]
Hey Grant, thanks for all your help so far 🙂

I've just tried being more explicit with the .glcoudignore and .gitignore but no luck there.

The repo I linked to has an `npm run deploy` command, which in the `package.json` file has the following:
```json
"main": "dist/index.js"
"scripts": {
  "deploy": "npx tsc && gcloud functions deploy helloWorld --runtime nodejs10 --trigger-http"
}
```
(I've updated it for my use-case with nodejs14)

This should compile the TS down to JS and then point to that file as the file to use in the deployment. It does appear that that is the case, as the error seems to match:
```
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Build failed: dist/index.js does not exist; Error ID: 9e84f54e
```

To reproduce, simply clone the [repo](https://github.com/golergka/gcf-typescript-template) and run the deploy command.

You're welcome to look at my code too, if that helps? https://github.com/jgunnink/workflow-cicd-demo/tree/master/functions/notify-github

It's very possible I'm missing something obvious here.

**Comment by teddybee** [comment]
I have the same problem.  I followed the official gts description, uploaded the zip file on the gcloud web page  without node_modules, build, and .gitignore. The result after several try, always this: 
```
status: {
code: 3
message: "Build failed: build/src/index.js does not exist; Error ID: 4b13a190"
}
```

**Comment by paulw11** [comment]
It looks like the issue is an assumption that if a file is `.gitignore`d then it shouldn't be deployed; I don't think that this is correct, as this issue shows.

It is reasonable not to want to commit the compiled .js files to git, but these files do need to be deployed (and conversely you may not want to deploy the .ts files).  

Perhaps there should either be:

* An option to ignore `.gitignore` and only honour `.gcloudignore`
* An option to override `.gitignore` for specific files/paths/patterns in `.gloudignore`.

Personally, I think the former makes more sense; `.gcloudignore` should be definitive, not additive to `.gitignore` but changing the default behaviour could be a breaking change, so it probably needs to be opt-in.

**Comment by jgunnink** [comment]
Hi, just following up on this issue. Wondering if there's any further info you need?

**Comment by grant** [comment]
Hi, thanks for the ping. It would help if full repo steps were included with the issue. We don't look at other repos for setup usually. Adding details within this GitHub issue would help. A minimal setup is best.

It looks like Cloud Build is not finding dist/index.js, so the first step would be to ensure its not ignored.

**Comment by jgunnink** [comment]
Sorry if I have been unclear. The crux of the issue is: if the compiled output is in the .gitignore, then the deployment will fail, regardless of if the file exists or not, with the message that the file doesn't exist.

If the compiled output file is _not_ in the gitinore then it works.

Ideally committing compiled code as part of git history is not ideal. Is this the intended behaviour?

**Comment by grant** [comment]
I think that issue is clear. The issue is with your gcloud setup. gcloud is ignoring your files.

Usually gcloudignore solves this. You can also use a separate Cloud Storage bucket with `--stage-bucket`. See https://cloud.google.com/functions/docs/deploying/filesystem

It doesn't seem like a Node Functions Framework issue, maybe a gcloud issue or setup issue.

Can you please provide full sets with a minimal sample in the original GitHub issue above, such that anybody can fully reproduce the error? No links to other repos/websites.

**Comment by jgunnink** [comment]
Hey @grant, sorry for the delay.

Here's the steps to reproduce. Using the following files...

1. `src/index.ts` file
```typescript
export const hello = (req: any, res: any) => {
  res.send("Hello, Typescript!");
};
```
2. `.gcloudignore` file
```
# This file specifies files that are *not* uploaded to Google Cloud Platform
# using gcloud. It follows the same syntax as .gitignore, with the addition of
# "#!include" directives (which insert the entries of the given .gitignore-style
# file at that point).
#
# For more information, run:
#   $ gcloud topic gcloudignore
#
.gcloudignore
# If you would like to upload your .git directory, .gitignore file or files
# from your .gitignore file, remove the corresponding line
# below:
.git
.gitignore

node_modules
#!include:.gitignore
```
3. `.gitignore`
```
node_modules/
dist/
```
4. `package.json`
```json
{
  "name": "typescript-function",
  "version": "1.0.0",
  "description": "A sample for Google Cloud Functions that uses Typescript.",
  "main": "dist/index.js",
  "scripts": {
    "start": "npx tsc-watch --onSuccess 'npx @google-cloud/functions-framework --target=hello'",
    "deploy": "npx tsc && gcloud functions deploy hello --runtime nodejs14 --trigger-http"
  },
  "author": "JK Gunnink",
  "license": "MIT",
  "devDependencies": {
    "@google-cloud/functions-framework": "^1.9.0",
    "tsc-watch": "^4.4.0",
    "typescript": "^4.3.4"
  }
}
```
5. `tsconfig.json`
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "outDir": "dist"
  },
  "include": ["src/**/*.ts"]
}
```

---

Once you have these files, to reproduce:
1.  At the root of the project directory, run `npx tsc` to compile your typescript to raw javascript
2. Then run `gcloud functions deploy hello --runtime nodejs14 --trigger-http --region australia-southeast1`

This will fail with the following output:
```
Deploying function (may take a while - up to 2 minutes)...failed.                                                                                            
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Build failed: dist/index.js does not exist; Error ID: 9e84f54e
```

3. In the `.gitignore` file, remove the `dist/` line.
4. Re run the `gcloud functions deploy hello --runtime nodejs14 --trigger-http --region australia-southeast1` command
5. The deployment succeeds.


This is where the bug lies. At all times, the .gcloudignore file should be sending the `dist/`, but it seems the cli is not obeying it, and instead using the .gitignore instead.

Which brings me back to the summary of this issue:

> When using Typescript to build and deploy a function, if the target dir/file is in the gitignore, then the deployment fails.

Thanks for your time and help!

**Comment by jgunnink** [comment]
With your comment here:
> It doesn't seem like a Node Functions Framework issue, maybe a gcloud issue or setup issue.

It does indeed seem to be related to gcloud cli. I wrote the steps out above for the fullness of the issue, and for future visitors to this issue. Should I raise an issue for the gcloud cli team? If this is not related to functions framework, I'm happy to do so - can you point me in the right direction? Cheers!

**Comment by teddybee** [comment]
> It does indeed seem to be related to gcloud cli. 
Its not just CLI related, I did the step on gcloud web admin, uploading the zip file, and it failed to deploy, if I haven't zip the dist folder as well.

**Comment by grant** [comment]
Thanks. The repro steps are really useful. I'm not sure of where the issue is located the moment.

The `npx tsc-watch --onSuccess` command seems pretty weird to do this every time we start the script.

I would also try running your function in a container and seeing if the error persists:

https://cloud.google.com/functions/docs/building/pack

If the error is there, then it's a FF issue. If not, it may be a Node buildpack issue.

**Comment by alexjmoore** [comment]
I think I might understand what is happening here.  In `.gcloudignore` file example you have the line at the end:
```
#!include:.gitignore
```
Despite starting with a # this actually is a command to tell `.gcloudignore` to also pull in entries from `.gitignore` and in there of course you are telling it to ignore `dist/` which is why it never makes it up for deployment.

So you could either remove that line or you could override the .gitignore elements you *do* want to be uploaded, you can do that for `dist/` with a `!dist/` after the `#!include` line, i.e. at the very end of he file, so the whole file will look like:

```
# This file specifies files that are *not* uploaded to Google Cloud Platform
# using gcloud. It follows the same syntax as .gitignore, with the addition of
# "#!include" directives (which insert the entries of the given .gitignore-style
# file at that point).
#
# For more information, run:
#   $ gcloud topic gcloudignore
#
.gcloudignore
# If you would like to upload your .git directory, .gitignore file or files
# from your .gitignore file, remove the corresponding line
# below:
.git
.gitignore

node_modules
#!include:.gitignore
!dist/
```
For more information on this, you can read more on the 'advanced topics' section at the bottom of this page: https://cloud.google.com/sdk/gcloud/reference/topic/gcloudignore

**Comment by jgunnink** [comment]
Thank you @alexjmoore this has solved the issue. In your link at the bottom of the post, there's an example section, which is where I originally took some of the example code I think
<img width="888" alt="image" src="https://user-images.githubusercontent.com/8016590/127759582-b4905dd6-0a6c-4f43-b4a4-a93e9e97d17b.png">

Perhaps the docs here could be amended to make it abundantly clear what's going on (for future readers).

Really appreciate the help, and you too @grant. Thanks 😃
