### ISSUE TITLE
Custom URL

### ISSUE THREAD

**Issue by AkashSCIENTIST** [GoogleCloudPlatform/functions-framework-nodejs#312]
How to add a custom URL/URI for the function while deploying? (like custom port, subdomain and path)

**Comment by grant** [comment]
Hey there, thanks for the question. I'm not sure where you are trying to deploy to.

- You can use the `PORT` variable for a custom port
- The function listens to all requests at `localhost:PORT/*`. The container can map external HTTP requests to that localhost URL. You can handle different paths within your function.

**Comment by grant** [comment]
LMK if there's anything else we can do. I'll close this bug for now.
