### ISSUE TITLE
Handling gzipped POST requests

### ISSUE THREAD

**Issue by reilly3000** [GoogleCloudPlatform/functions-framework-nodejs#313]
I've created a Cloud Function to receive webhooks from a service that POSTs requests using gzip compression. Here are the relevant headers included with its requests:
```
'content-type': 'gzip/json',
'content-encoding': 'gzip',
 accept: 'application/json',
 'transfer-encoding': 'chunked',
```
In a typical express application the bodyParser middleware should inflate gzip compression automatically. In this case when I call `console.log(JSON.stringify(req.body))` I get the raw compressed bytes. Is there a way to process this request so that I can log the uncompressed request body? Otherwise can anybody recommend a clever way to gunzip the request in my function body?

example output:

```
jsonPayload: {
  type: 'Buffer',
  data: [
  0: 123
  1: 34
  2: 112
  3: 99
  4: 95
  5: 115
  6: 116
  ...```

**Comment by grant** [comment]
Hi there,
Sorry for not replying sooner.

Perhaps you can use some middleware to inflate the gzipped contents automatically?

- https://medium.com/google-cloud/express-routing-with-google-cloud-functions-36fb55885c68
- http://expressjs.com/en/resources/middleware/body-parser.html
- https://stackoverflow.com/a/12776856

Hope that helps.

@ace-n might have a sample for this too.

Closing as part of triaging, but feel free to re-open if there's an issue with the Functions Framework or if nothing seems to work and there's further repro details :)
