### ISSUE TITLE
"Ignoring exception from a finished function"

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/functions-framework-nodejs#32]
## Problem

I'm running into a message from the framework on "Ignoring exception from a finished function". Because the framework is catching this exception, I'm not sure what the problem is.

## Solution

Do not hide errors, assume developers will not use try/catch blocks.

## Reproduction Details

Adding a `console.error(err)` below where the function framework generates this message, I get actionable details:

```
Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
```

By default this kind of message should be shown to the developer.

In practice, this error is being thrown in my logging code when the function attempts to send a message to Stackdriver.

**Comment by grayside** [comment]
I don't rule out helping later, but just to snapshot something:

```
const bunyan = require('bunyan');

// Imports the Google Cloud client library for Bunyan
const {LoggingBunyan} = require('@google-cloud/logging-bunyan');
// Creates a Bunyan Stackdriver Logging client
const loggingBunyan = new LoggingBunyan();
const logger = bunyan.createLogger({
 name: 'run.googleapis.com%2F',
 streams: [
   {stream: process.stdout, level: 'info'},
   loggingBunyan.stream('info')
 ]
});

const client = new tasks.v2.CloudTasksClient();

// Reuse the loaded queue object for future requests.
let queue;

exports.logme = async (req, res) => {
 logger.warn("What's refrigeration?");
};
```

**Comment by swalkowski** [comment]
@stew-r You are right that we want to avoid the situation where any unhandled error would result in a cold start.

I don't see a problem with logging the error as a part of console.log which prints `Ignoring exception from a finished function`. The original rationale for not printing the error might have been to decrease logging noise in situations where this indicates a non-critical error generated outside of developer's control. But I agree that transparency is more important.
