### ISSUE TITLE
Error when running v1.10

### ISSUE THREAD

**Issue by dpalmasan** [GoogleCloudPlatform/functions-framework-nodejs#326]
Hello, I tried to run `npx @google-cloud/functions-framework -target=helloWorld` on a MacOS:

```
19.6.0 Darwin Kernel Version 19.6.0: Tue Jun 22 19:49:55 PDT 2021; root:xnu-6153.141.35~1/RELEASE_X86_64 x86_64
```

When using `google-cloud/functions v1.10` I got the following error:

```
Error: Cannot find module './middleware/cloudevent_to_background_event'
Require stack:
```

```
code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/dpalma/Documents/hello-world/functions/node_modules/@google-cloud/functions-framework/build/src/server.js',
    '/Users/dpalma/Documents/hello-world/functions/node_modules/@google-cloud/functions-framework/build/src/index.js'
  ]
```

Installed previous version `1.9.0` and it worked. Might be an issue or some missing dependency? I couldn't find anything related on the other issues.

**Comment by maelcaldas** [comment]
Same here.

Previous versions of functions-framework works locally, but production deployments does not work anymore. All new deployments fail with this same error message. Nothing changed from the last code deployed successfully.

**Comment by grant** [comment]
Thanks for the report. This looks like the same issue as https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/326.

I'll update the status there and close this issue.
