### ISSUE TITLE
TypeScript + Nodemon + vscode debugger

### ISSUE THREAD

**Issue by dsstewa** [GoogleCloudPlatform/functions-framework-nodejs#334]
Has anyone successfully  been able to attach the vscode debugger to the nodemon deamon with the typescript example given? We are able to get it to attach, as soon as there was a file change or re-load it would detach. 

David

**Comment by dsstewa** [comment]
"start": "./node_modules/.bin/env-cmd node --inspect node_modules/@google-cloud/functions-framework -sour ce=build/src/ --target=helloWorld",

Appears to fix the issue, updating the package.json

**Comment by grant** [comment]
Thanks. We have a few discussions around this issue. Of course we don't have samples for every combination of other tech.

For example: https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/254

It seems like you resolved figuring it out. Closing. :)
