### ISSUE TITLE
Move `main()` out of `index.ts`

### ISSUE THREAD

**Issue by matthewrobertson** [GoogleCloudPlatform/functions-framework-nodejs#350]
Currently our [bin scripts](https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/package.json#L33-L36) point to the same root `index.ts` file that exposes our public API. The implication is that developers cannot `import {foo} from "@google-cloud/functions-framework"` without spinning up the webserver. This adds some complexity to local development and testing workflows.

I think a reasonable change would be to extract the initialization logic into a separate file (eg `main.ts`) that spins up the webserver. Then update our [bin scripts](https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/package.json#L33-L36) to point to that file.

**Comment by grant** [comment]
> @grant I think you are discussing a slightly different problem. The problem here isn't related to type declarations. The concern is package's `"main"` will includes the code to start up the express server. This was always a problem, but it is worse with DFS because we are asking developers to import a runtime construct in their application code. As soon as they do this:
> 
> ```js
> var x = require('@google-cloud/functions-framework');
> ```
> 
> the express server will start. Which will make it hard to do things like write unit tests.

Ah, that makes more sense. 👍🏻
