### ISSUE TITLE
Better type annotation for cloudevent functions

### ISSUE THREAD

**Issue by matthewrobertson** [GoogleCloudPlatform/functions-framework-nodejs#351]
Now that we have the declarative functions signatures API we should be able to use the type annotations in https://github.com/googleapis/google-cloudevents-nodejs to provide a strong type information for cloudevent data payloads.

**Comment by grant** [comment]
How did we want the interface to be for the optional type annotation for CloudEvent data types?

Would this work for both declarative and non-declarative functions?

I could imagine a couple JS interfaces:

### Option 1

User dependency on `@google/events`:

```ts
const {toLogEntryData} = require('@google/events/cloud/audit/v1/LogEntryData');

export function (cloudevent, toLogEntryData) => {
  console.log(cloudevent.data); // should have types
};
```

### Option 2

FF dependency on `@google/events`:

```ts
exports.helloCloudEvents = async (cloudevent, 'google.events.cloud.audit.v1.LogEntryData') => {
  console.log(cloudevent.data); // should have types
};
```
