### ISSUE TITLE
Re-export Functions Interface

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/functions-framework-nodejs#355]
We change the exported types for this repo in a previous PR (I think).

https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/347/files#r724614498

The types are declared here:

https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/package.json#L10

They should probably point back to this file:

https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/src/functions.ts

We should likely re-add these types, since developers would be losing type information otherwise.

**Comment by matthewrobertson** [comment]
I made this change intentionally. Nothing should have changed for developers because we re-export everything from `functions.ts` in `index.ts`.

**Comment by grant** [comment]
Fixed with https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/354
