### ISSUE TITLE
Documentation: Unclear how to use events signature-type and test pubsub

### ISSUE THREAD

**Issue by comolongo** [GoogleCloudPlatform/functions-framework-nodejs#37]
Hi,
I was able to setup and do local testing using http signature. However my goal is to do local development on a cloud function that consumes PubSub. What is the best development workflow for this?

I was thinking I may need to set signature-type to event, and somehow pass in a mock pubsub event object, how the current documentation doesn't give me many clues. Could someone point me the way?

Thanks!

**Comment by grant** [comment]
Hey @comolongo, 
Can you see if this sample helps you?
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/functions/pubsub/test/index.test.js#L32

Looks like it uses the HTTP signature, but it could be useful for a local dev workflow.
Maybe @ace-n could provide more detail.

**Comment by Sabyasachi2k** [comment]
hi,
Any example for the signature-type event would really help. that example is for publishing. I have the subscribe function and I am unable to call the function to test it.

**Comment by grant** [comment]
@Sabyasachi2k Does this guide help?

https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/40/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8

We're working on an event guide. I agree it would be useful.

**Comment by Sabyasachi2k** [comment]
@grant Thank you for the link.
Go one question. 
1. I am able to call the function using the instruction given, however instead of the variable being available in the pubSubEvent variable, its available on the context variable. Any idea what needs to be done
function helloPubSub(pubSubEvent, _context) {
console.log (" the data passed is " + JSON.stringify(pubSubEvent) + ", " + JSON.stringify(_context));
}

**Comment by grant** [comment]
> I am able to call the function using the instruction given, however instead of the variable being available in the pubSubEvent variable, its available on the context variable. Any idea what needs to be done

I don't know at the moment.

Node functions for Pub/Sub triggers should look like this:
https://cloud.google.com/functions/docs/calling/pubsub#sample_code

If we think there is a bug with following that code, we should file a bug with expected/actual behavior that might be in this framework or elsewhere.

**Comment by Sabyasachi2k** [comment]
Thanks a lot @grant 
Is there a location where the bug report can be done.

**Comment by grant** [comment]
> Thanks a lot @grant
> Is there a location where the bug report can be done.

There's a **feedback** button on the page for creating the bug report.
