### ISSUE TITLE
CloudEvent registration method should be camelCase

### ISSUE THREAD

**Issue by matthewrobertson** [GoogleCloudPlatform/functions-framework-nodejs#378]
"Cloud Event" is two words so the "E" should be capitalized:

```typescript
import * as functions from '@google-cloud/functions-framework';

functions.cloudEvent('helloCloudEvent', (cloudEvent) => {
  console.log('Hello, CloudEvent!');
});
```

**Comment by grant** [comment]
Nice catch. `cloudEvent` should be the correct pascal case. 👍🏻 

Note: CloudEvent is one word, but the outcome of using `cloudEvent` is the same.

https://cloudevents.io/
