### ISSUE TITLE
Loading .env when using functions-framework

### ISSUE THREAD

**Issue by braeden123** [GoogleCloudPlatform/functions-framework-nodejs#38]
Hey, I might have missed something in the documentation, but is there a flag like ` --env-vars-file ./config/.env` so that it can simulate the deployment of an actual GCF with environmental vars. 

Thanks so much!

**Comment by stew-r** [comment]
We don't have such a feature for the framework as the goal is to give you the functionality that's actually used in the Cloud Functions environment. In the Cloud Functions environment, the environment variables are set on the container (vs. through a mechanism like the one you describe).

The easiest approach to solve your issue is to set the environment variables on your local machine/dev environment. You could write a small script that automates setting environment variables based on the `.env` file

**Comment by QuantumInformation** [comment]
I just export like this:

`    "emulate:functions": " export DATASTORE_EMULATOR_HOST=http://localhost:8081 && forever -c 'node --inspect' node_modules/@google-cloud/functions-framework --target=api ",
`

**Comment by afilipko** [comment]
Its also possible to do this with [env-cmd](https://www.npmjs.com/package/env-cmd)
command will look like this
`./node_modules/.bin/env-cmd -f ../environment.json yarn start`

**Comment by relymd-djk** [comment]
Here is my set up to use my yaml env definitions for cloud functions cli with functions-framework:

`"start": "yaml2json env.foo.yaml >.env.json &&  env-cmd -r ./.env.json functions-framework --target=targeFunc",
"deploy": "gcloud functions deploy myFunction --entry-point targeFunc  --env-vars-file ./env.foo.yaml "`

**Comment by j0nl1** [comment]
Here is another solution using yamlenv package.

`"start": "node -r yamlenv/config node_modules/@google-cloud/functions-framework --target=helloWorld"`
`"deploy": "gcloud functions deploy helloWorld --entry-point helloWorld --env-vars-file ./env.yaml"`

**Comment by anborg** [comment]
>You could write a small script that automates setting environment variables based on the .env file

My gcloud function in java is not picking up env.yml .  I hope google incorporates env variables functionality for local testing as well

**Comment by psaul20** [comment]
Any guidance on how to do this with Python? A bit frustrating that it's not a passable flag when I start a functions framework instance. I am able to specify --env-vars-file=.../.env.yaml when I run gcloud function deploy from command line...

**Comment by anothermh** [comment]
> Any guidance on how to do this with Python?

Probably best to ask at https://github.com/GoogleCloudPlatform/functions-framework-python.

**Comment by gregorvand** [comment]
For Node, it seems to work using the conventional `dotenv` package and a .env file locally
This could then be kept in sync with a .env.yml for deployment

Not ideal to keep two files in check, but achieves the same end for both envs and use `||` where needed

**Comment by victor871129** [comment]
Use yamlenv: Call the root env file `env.yaml`, execute `npm install yamlenv` and add this as early as possible in your application `require('yamlenv').config()`

**Comment by akiicat** [comment]
Here is a bash solution

```sh
# Parse yaml in shell script
# https://stackoverflow.com/questions/5014632/how-can-i-parse-a-yaml-file-from-a-linux-shell-script
function parse_yaml {
    local prefix=$2
    local s='[[:space:]]*' w='[a-zA-Z0-9_]*' fs=$(echo @|tr @ '\034')
    sed -ne "s|^\($s\):|\1|" \
        -e "s|^\($s\)\($w\)$s:$s[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p" \
        -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p"  $1 |
    awk -F$fs '{
        indent = length($1)/2;
        vname[indent] = $2;
        for (i in vname) {if (i > indent) {delete vname[i]}}
        if (length($3) > 0) {
            vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
            printf("%s%s%s=\"%s\" ", "'$prefix'",vn, $2, $3);
        }
    }'
}

bash -c "$(parse_yaml .env.yaml) functions-framework --target entrypoint --debug"
```

**Comment by triwats** [comment]
From my experience, I had this set as a `.env.local` and it was not picked up. Renaming it to `.env` seemed to work (regardless of changing `path`). Will try to update this when finished with more debugging.
