### ISSUE TITLE
Document the unit testing story

### ISSUE THREAD

**Issue by matthewrobertson** [GoogleCloudPlatform/functions-framework-nodejs#387]
We should write some internal guide that explains how to unit test functions. Things we should address:

- Make sure declarative function signatures provides a mechanism for customers to easily invoke functions in tests
- Writing integration tests for the express handlers with [supertest](https://www.npmjs.com/package/supertest)

**Comment by ace-n** [comment]
N.B: there is an (existing) doc page [here](https://cloud.google.com/functions/docs/bestpractices/testing).
