### ISSUE TITLE
CloudEvent traceparent extension not set for structured content requests

### ISSUE THREAD

**Issue by matthewrobertson** [GoogleCloudPlatform/functions-framework-nodejs#394]
When a `traceparent` header is sent with a structured CE request, it is not properly set as an extension attribute of the CE we pass to the customer's function.

We have [a unit test to validate this use case](https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/test/integration/cloud_event.ts#L57-L66). It only passes because the `traceparent` field is already set to the expected value in the [TEST_CLOUD_EVENT](https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/test/integration/cloud_event.ts#L28). We should probably update all the traceparent tests to use a different header value than we use in the `TEST_CLOUD_EVENT`.

**Comment by grant** [comment]
I wouldn't consider this a bug, as we're supporting tracing for normal binary CloudEvents that we use in Eventarc. Adding support for structured CEs and a test sounds reasonable, although it won't impact GCP developers.

**Comment by matthewrobertson** [comment]
The test already exists: https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/test/integration/cloud_event.ts#L57-L66

And it passes even though the functionality isn't implemented. We should either fix this or delete the test.
