### ISSUE TITLE
function deployment failing intermittently

### ISSUE THREAD

**Issue by sanjayngNegi** [GoogleCloudPlatform/functions-framework-nodejs#410]
I am trying to add typescript to my existing project
earlier I was using source code URLs(`https://source.developers.google.com/projects/....`) for deployment and was having no issues.
but now that I am trying to add typescript I have to build and deploy local source
and deployment seems to fail intermittently with errors like 

Error: Cannot find module './middleware/cloudevent_to_background_event'
Error: Cannot find module 'firebase-admin'

Folder structure
![image](https://user-images.githubusercontent.com/78856900/147145263-eb8d4190-721c-4c97-beef-e393a177721f.png)

I am only transpiling src folder in-place no specific output folder and importing the functions from src folder to outer index.js
 here is my package.json

```
{
  "name": "functions",
  "scripts": {
    "build": "tsc",
    "build:watch": "tsc --watch",
    "test": "npm run build && jest --coverage --silent",
  },
  "main": "index.js",
  "engines": {
    "node": "12"
  },
  "dependencies": {
    "@google-cloud/functions-framework": "^1.6.0",
    "@google-cloud/pubsub": "^0.18.0",
    "@google-cloud/tasks": "^2.3.5",
    "firebase-admin": "^9.5.0",
    "firebase-functions": "^3.13.1",
    "firebase-tools": "^9.20.0",
  },
  "devDependencies": {
    "eslint": "^7.26.0",
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-plugin-import": "^2.22.1",
    "firebase-admin": "^9.5.0",
    "firebase-functions": "^3.13.1",
    "firebase-functions-test": "^0.2.3",
    "jest": "^26.6.3",
    "typescript": "^3.8.0"
  }
}
```

here is my TS config
```
{
    "compilerOptions": {
      "module": "commonjs",
      "noImplicitReturns": true,
      "noUnusedLocals": true,
      "sourceMap": true,
      "strict": true,
      "target": "es2017",
      "allowJs": true,
      "skipLibCheck": true,
    },
    "compileOnSave": true,
    "include": ["src"],
    "exclude": ["src/**/*.js"]
  }
```
  .gitIgnore
```
*/package-lock.json
*/node_modules/*
node_modules/*
firebase.json
firebase-export-metadata.json
*.log
.firebaserc
*/input.txt
.DS_Store
*/coverage/*
coverage/*
*/__tests__/.*
src/**/*.js
src/**/*.js.map
!src/**/*.test.js
```
.gcloudignore
```
.gcloudignore
.git
.gitignore
node_modules
```
most wierd part is deployment is failing intermittently and for both my normal js functions as well as ts functions

here is the gcloud command i am using
```
sudo gcloud functions deploy "$func_name" \
    --project my_project \
    --runtime nodejs12 \
    --allow-unauthenticated \
    "$trigger" \
    "$env_vars";
```

**Comment by matthewrobertson** [comment]
Sorry to hear you are having troubles @sanjayngNegi. A few things I notice about your app that I would suggesting doing differently:

1. you should update to the latest version of the functions framework in your package.json
```
"@google-cloud/functions-framework": "2.1.0",
```
2. I suggest you always include your `package-lock.json` when deploying cloud functions (ie remove `*/package-lock.json` from you `.gitignore`. This ensures the packages that get installed will match what you are using when you test locally. It will also improve the performance of your build.
3. add a `gcp-build` script in your `package.json` to compile your Typescript:
```
"scripts": {
    "build": "tsc",
    "build:watch": "tsc --watch",
    "test": "npm run build && jest --coverage --silent",
    "gcp-build": "npm run build"
  },
```
That last step is an API supported by our [nodejs buildpack](https://github.com/GoogleCloudPlatform/buildpacks/blob/main/cmd/nodejs/npm_gcp_build/main.go#L88) for adding custom build steps. Unfortunately, it is not well documented right now.

**Comment by sanjayngNegi** [comment]
@matthewrobertson thanks for suggestions, tried deploying after applying these changes but deployment is still breaking for same function its like passed 3-4 times then suddenly it fails tried updating gcloud sdk also but same thing sometimes passes sometime fails.

**Comment by sanjayngNegi** [comment]
Issue is not getting reproduced now, closing
