### ISSUE TITLE
Handle thrown exceptions consistently with other frameworks

### ISSUE THREAD

**Issue by anniefu** [GoogleCloudPlatform/functions-framework-nodejs#422]
There are two scenarios where Node behaves different from most other Functions Frameworks
1. User throws an exception in their function code
2. User returns an error in their event-driven function code (HTTP functions don't have return parameters)

Most frameworks will return HTTP status code 500 in both those cases, and hide the exception/error message from the invoker.

Node returns 200 status code and returns the exception/error message in the response body. We should modify node to return 500 and omit the exception/error message from the response body to avoid leaking debug information to the invoker. We should log the message instead.

**Comment by grant** [comment]
I'm seeing a 500 error already being sent in Node.

```js
/**
 * Send "Hello, World!"
 * @param req https://expressjs.com/en/api.html#req
 * @param res https://expressjs.com/en/api.html#res
 */
exports.helloWorld = (req, res) => {
  throw new Error('hi');
  res.send('Hello, World!');
};
```

Response:

```
curl -I localhost:8080
HTTP/1.1 500 Internal Server Error
X-Google-Status: crash
Content-Type: text/html; charset=utf-8
Content-Length: 2
ETag: W/"2-witfkXg0JglCjW9RssWvTAveakI"
Date: Thu, 03 Feb 2022 20:48:32 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

Location of sending error:

https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/src/logger.ts#L46

I thought maybe we would have to do a:

`res.status(500);`

but it doesn't look necessary.

**Comment by grant** [comment]
May need another pair of eyes to understand the failures / expected result.
