### ISSUE TITLE
Add support for custom environment variables

### ISSUE THREAD

**Issue by stripthis** [GoogleCloudPlatform/functions-framework-nodejs#43]
Similar to `gcloud functions deploy --set-env-vars FOO=bar,BAR=foo` this would facilitate testing running google functions that uses environment variables using functions-framework.

**Comment by stew-r** [comment]
This is similar to #38 -- the Functions Framework is not an emulator for the `gcloud` command-line tool and we don't plan to support this. I proposed a couple of solutions in #38.

**Comment by stripthis** [comment]
Sounds good thanks.
