### ISSUE TITLE
How to debug functions with the new functions-framework?

### ISSUE THREAD

**Issue by arbassic** [GoogleCloudPlatform/functions-framework-nodejs#47]
Hi Guys!

It is probably a newbie question but I have to ask it directly here:

with old "functions" library it was possible to debug/inspect functions on a local machine by:

`functions deploy helloWorld`
`functions inspect helloWorld --port 5000`

... and attaching to the port with IDE.

Is there some sort of similar way to do so with the new functions-framework?

**Comment by stew-r** [comment]
Yes, check out https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/15.

We have an open action item to document these instructions in the extended docs that @grant is setting up -- https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/docs/README.md

Pull requests encouraged! :)

**Comment by grant** [comment]
Stewart is writing a guide. Here is an excerpt:

 ## Debugging functions using the Functions Framework

 The Functions Framework works with  standard tooling that you might use when writing a function for a Node.js environment. You can attach a debugger to your function.

 1. Write a Node.js function:

 ```js
exports.helloWorld = (req, res) => {
  res.send('Hello, World');
};
```

 2. Install the Functions Framework:

 ```sh
npm install @google-cloud/functions-framework
```

 3. Launch the Functions Framework and attach a debugger:

 ```sh
node --inspect node_modules/@google-cloud/functions-framework --target=helloWorld
...
Debugger listening on ws://127.0.0.1:9229/5f57f5e9-ea4b-43ce-be1d-6e9b838ade4a
For help see https://nodejs.org/en/docs/inspector
Serving function...
Function: helloWorld
URL: http://localhost:8080/
```

 You can now use an IDE or other tooling to add breakpoints, step through your code and debug your function.

**Comment by stew-r** [comment]
Added instructions: https://github.com/GoogleCloudPlatform/functions-framework-nodejs/tree/master/docs
