### ISSUE TITLE
Node 18

### ISSUE THREAD

**Issue by RevealedFrom** [GoogleCloudPlatform/functions-framework-nodejs#476]
How imminent will Node 18 be supported?

I need `fetch`.

**Comment by jama22** [comment]
Pretty soon, we had to do some updates to the builder to support Ubuntu 22 as the base image. Should be available before end of month

**Comment by RevealedFrom** [comment]
Thanks for bringing it to v18.12.1. Is there a regular review to keep it closer to the latest Node version?

`fetch` doesn't work properly in v18.12.1, but it's ok in v18.14.2 or v18.15.0.
