### ISSUE TITLE
CloudFunction and EventContext are not exported members

### ISSUE THREAD

**Issue by jacflesher** [GoogleCloudPlatform/functions-framework-nodejs#499]
CloudFunction and EventContext are not exported members of module @google-cloud/functions-framework.  Yet someone from Google recommended I use them for authentication in an Angular application.  Angular seems to be the unwanted stepchild of the samples and code snippets offered on Google Cloud docs.  I can't find examples for Angular anywhere.  

https://www.googlecloudcommunity.com/gc/Serverless/Cloud-Run-metadata-auth-Blocked-loading-mixed-active-content/m-p/504565#M1017

**Comment by josephlewis42** [comment]
Hi @jacflesher sorry to hear about your bad experience with the community support site. It looks like they might have been targeting an old versions of the Functions Framework.

To answer your question from the other site, you can use the metadata server to get an authentication token associated with the service account for a function and use that to authenticate to your service: https://cloud.google.com/functions/docs/securing/function-identity#using_the_metadata_server_to_acquire_tokens
