### ISSUE TITLE
Missing Tag / Release

### ISSUE THREAD

**Issue by charles-salmon** [GoogleCloudPlatform/functions-framework-nodejs#50]
I've just noticed that the latest version published to the npm registry is [`1.1.1`](https://www.npmjs.com/package/@google-cloud/functions-framework/v/1.1.1). The most recent tag which I see here on GitHub is `v1.1.0`.

Is it perhaps possible that a manual release didn't quite go to plan?

**Comment by stew-r** [comment]
Adding @grant @rishisharma-google since I think we need to cut a new GitHub release to match this version.

**Comment by grant** [comment]
I've cut a new release.
Ideally whoever npm publishes does this at that time.

https://github.com/GoogleCloudPlatform/functions-framework-nodejs/releases/tag/v1.1.1
