### ISSUE TITLE
Watching for changes & Typescript

### ISSUE THREAD

**Issue by tomardern** [GoogleCloudPlatform/functions-framework-nodejs#52]
Hi,

As this is the recommended way to run functions locally, is there a way to use Typescipt and to watch files?

Thanks,

**Expected Behaviour:** 
Running `functions-framework --watch` would restart the functions framework if any of the *.js files in the app (eg the main index.js and it's dependancies) change

**Actual Behaviour:**
New feature

**Steps to Reproduce the Problem**
New feature

**Comment by grant** [comment]
Hi @tomardern,

Please look at this project where I built functions in TypeScript and tested them locally with the Functions Framework:
https://github.com/googlesamples/functions-as-a-service

---

I'll keep this issue open so that we can document the setup process here.

**Comment by tomardern** [comment]
thanks @grant for the reply, and the sample.

If the `functions-framework` had a flag (maybe `--watch`), then it'll be super easy to integrate typescript. (I use something similar to the below for firebase!)

```
./node_modules/.bin/tsc --watch & functions-framework --watch
```

**Comment by grant** [comment]
@tomardern If you'd like file a feature request, can you please include more details in the issue by editing the first comment? If you think that the `tsc --watch` setup is fine, we could close this issue?

I looked for a similar feature in the firebase CLI and couldn't find one. Can you provide a link?

**Comment by tomardern** [comment]
Hi @grant . More than happy for a feature request - do you have a template?

I think firebase has it built in using the `firebase serve` command. The `tsc --watch` setup is good for me :)

**Comment by grant** [comment]
Could you edit the top comment and follow this template?

---

## Expected Behavior


## Actual Behavior


## Steps to Reproduce the Problem

1.
1.

**Comment by tomardern** [comment]
Updated @grant! Thanks.

**Comment by QuantumInformation** [comment]
I just use

    "debug-watch": "npx tsc-watch --onSuccess 'npx @google-cloud/functions-framework --target=sendMail'"

**Comment by golergka** [comment]
@QuantumInformation thanks for that workaround, works perfectly! I have just compiled a [minimalistic example of a Typescript GCF project](https://github.com/golergka/gcf-typescript-template/tree/master) and used it there as well.

**Comment by QuantumInformation** [comment]
Yeah its easier to understand.

**Comment by tomardern** [comment]
Based on @QuantumInformation's excellent answer, we've ended up using the following:

```
"dev": "tsc-watch --onSuccess 'functions-framework --target=testFuction'"
```

Then just `npm run dev`.

Bonus: If you want to add the typescript source files to a different folder `/app`, then:
- In tsconfig.json change `"outDir": "./dist"` and `"rootDir":"./app"`
- In package.json change to `"main":"./dist/index.js"`

**Comment by QuantumInformation** [comment]
aww Thanks, for future ref I explain why I did it this way here:

https://youtu.be/PG-oqa0aSvQ?t=259

**Comment by QuantumInformation** [comment]
Can we close this?

**Comment by tomardern** [comment]
Sure. Closing. :)
