### ISSUE TITLE
Adding a source flag to get more flexibility on execution

### ISSUE THREAD

**Issue by notapineapple** [GoogleCloudPlatform/functions-framework-nodejs#54]
As i'm a user of babel (for example) i always transpile my code to the correct runtime Node.js functions version, i like to have my package scripts with the serve, the actually behavior of this library is trying to get the function from the `process.cwd()`.
It would be more flexible adding a source flag, cause' in my case, i do always have a `dist` folder from babel, with the transpiled code. I like to keep my source tree organized, including my scripts.

I've already made the PR.

**Comment by dupski** [comment]
+1 for being able to use a lib / dist directory for code - its pretty ugly putting source in the root directory and not good for any serious development.

As a workaround I use an npm script with
`"devserver" : "cd lib && @google-cloud/functions-framework --target=` ... etc

**Comment by medelman17** [comment]
I would also like to express support for #53 similar reasons--i.e., webpack/typescript support. @grant -- can we restart that discussion on larger implications?

**Comment by grant** [comment]
I agree that this would be a useful feature. I need to check with the PM to see if we can support this parameter (for all languages).

For the project I used at Google I/O that uses TypesScript and a `src/` directory, I just used one `index` file in the main directory:
https://github.com/googlesamples/functions-as-a-service

I'll check with the PM today and see what he says.

**Comment by grant** [comment]
Should have closed this earlier.
See the `--source` flag in the README.
