### ISSUE TITLE
Release latest version

### ISSUE THREAD

**Issue by TriPSs** [GoogleCloudPlatform/functions-framework-nodejs#547]
Can the latest version with the cloudevents@7 update be released? We can't release functions for nodejs 20 atm as cloudevents@6 does not support nodejs 20.

**Comment by garethgeorge** [comment]
Thanks for letting us know you're being blocked by this, I've gone ahead and merged https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/546 for the `v3.2.1` which now available on npm and includes cloudevents@7.

I'll go ahead and resolve this but please followup if you still have any issues with the new release.
