### ISSUE TITLE
Nodejs 14 Deprecation 

### ISSUE THREAD

**Issue by rwesley23** [GoogleCloudPlatform/functions-framework-nodejs#579]
Hello everyone, we currently have approximately 500 functions deployed for Node.js 14. According to the Google Cloud Console, Node.js 14 is scheduled to be deprecated on January 30, 2024. The message suggests updating these functions to the latest available runtime version. I would appreciate some clarification on whether our functions will still be able to execute on February 1, or if they will continue to run but won't allow deployment updates. 

Thank you!

**Comment by jama22** [comment]
Hey @rwesley23 , this is the open source issue tracker for the node.js functions framework project. It generally should not be used for technical support and/or guidance for Cloud Functions related issues. For the most definitive answer, I would suggest reaching out to GCP Support

That said, I'd point you to https://cloud.google.com/functions/docs/runtime-support , which describes what is expected to happen at each stage of the runtime support lifecycle. 

> During the deprecation period, **you can generally continue to create new functions and update existing functions using the runtime**. You should use this time to migrate functions that use the deprecated runtime to a more up-to-date runtime.

Hope that helps
