### ISSUE TITLE
Functions Framework v3.4.0 breaks logging in Firebase projects

### ISSUE THREAD

**Issue by lox** [GoogleCloudPlatform/functions-framework-nodejs#617]
See https://github.com/firebase/firebase-functions/issues/1580

Full reproduction at https://github.com/patientnotes/gcp-case-52054407

**Comment by jrmfg** [comment]
Thanks - fixed in #620 - we still need to do a release so I'll leave this open for now.

**Comment by jrmfg** [comment]
Tested, this works great. Going to cut the release.

**Comment by jrmfg** [comment]
Fixed in 3.4.1.

**Comment by jrmfg** [comment]
To handle log levels correctly in log explorer, use [structured logging](https://cloud.google.com/functions/docs/samples/functions-structured-logging) (or the firebase logging library); all the nodejs `console` logging facilities are just [writing a colored message to either stdout or stderr,](https://cloud.google.com/functions/docs/samples/functions-structured-logging) so there's little we can do to tag logs with these APIs with the correct log level

We've never handled `console.warn` in cloud logging/structured logs.  Before 3.4.0, this showed as a log at "default" level. 
 After 3.4.0, this shows as an error, which is not really correct either.  Neither have ever shown `console.warn` as a warning.  

We could consider changing this to show default log levels for unstructured logs as before 3.4.0 if this is breaking you.  Would you prefer that?

**Comment by jrmfg** [comment]
We could also try to be clever and use the ANSI color codes at the start of the string to try to figure out if it's a warn or error, and add structured logging accordingly. might be cool, but also isn't backwards compatible.

**Comment by jesus-velasco-inditex** [comment]
Well, we will change to structured logging using Google Library, but is there a way to put a message and extra information without put the message in a sublevel as a simple string do it?

![5](https://github.com/user-attachments/assets/b9d4cc73-30ba-4957-9a53-ad9a47edee78)
![4](https://github.com/user-attachments/assets/e90351d3-548a-43a9-8fbb-4ca55616346f)

**Comment by jrmfg** [comment]
> but is there a way to put a message and extra information without put the message in a sublevel as a simple string do it?

I'm not sure what you mean - the code you provided looks good, what problem are you having with it?

**Comment by jrmfg** [comment]
rolled back the stderr change in #625; it should land in 3.4.2.
