### ISSUE TITLE
Just wanted to announce the functions-framework SO tag!

### ISSUE THREAD

**Issue by QuantumInformation** [GoogleCloudPlatform/functions-framework-nodejs#63]
Posted here:

https://stackoverflow.com/questions/57176702/cloud-function-url-doesnt-work-after-deployment/57176779#57176779

**Comment by grant** [comment]
Thanks @QuantumInformation!
If it gets more traction, maybe it would be useful to add a badge with a link in this repo.

**Comment by QuantumInformation** [comment]
Added a 2nd question

https://stackoverflow.com/questions/57884072/how-to-change-baseurl-when-using-npm-lib-google-cloud-datastore
