### ISSUE TITLE
SSL certificates

### ISSUE THREAD

**Issue by olavgm** [GoogleCloudPlatform/functions-framework-nodejs#66]
Hi,

Since this framework can be run in more environments than Google Cloud Functions, is there a way to add SSL certificates to it? I can't find anything in the documentation.

Thanks!

**Comment by squee1945** [comment]
Can you describe in more detail the issue you're facing?

**Comment by olavgm** [comment]
> Can you describe in more detail the issue you're facing?

I want to run some functions on my own server, using my own domain, with SSL certificates from LetsEncrypt. Something like this, but Functions Framework instead of Express https://itnext.io/node-express-letsencrypt-generate-a-free-ssl-certificate-and-run-an-https-server-in-5-minutes-a730fbe528ca

**Comment by stew-r** [comment]
Let's leave this open and see if other users have similar needs. My current take on this is that it's a pretty specialized use case and we shouldn't modify the Functions Framework to support this.

That said -- the code is open source so you could easily fork and implement this.

**Comment by grant** [comment]
I think you're asking to use SSL certs like this this:

```js
var privateKey = fs.readFileSync( 'privatekey.pem' );
var certificate = fs.readFileSync( 'certificate.pem' );

https.createServer({
    key: privateKey,
    cert: certificate
}, app).listen(port);
```

For custom SSL certs, I think we'd need to change the `getServer` method to accept options, which we don't do currently:

https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/src/invoker.ts#L576

**Comment by olavgm** [comment]
> I think you're asking to use SSL certs like this this:
> 
> ```js
> var privateKey = fs.readFileSync( 'privatekey.pem' );
> var certificate = fs.readFileSync( 'certificate.pem' );
> 
> https.createServer({
>     key: privateKey,
>     cert: certificate
> }, app).listen(port);
> ```

Yes, that's exactly what I want and what I have right now using Express. I just want to move the service to Functions-Framework keeping SSL on my domain name.

**Comment by grant** [comment]
I think you'll have to use Cloud Run instead of Cloud Functions for the next few months at least to support this feature to be honest.

**Comment by grant** [comment]
This issue was also filed here on the Google Issue Tracker:
http://issuetracker.google.com/71505684

**Comment by TiffanyBurnsFork** [comment]
Is this option still unavailable? I'm wanting to do the same thing but haven't figured out how.

**Comment by grant** [comment]
@TiffanyBurnsFork Would a solution for adding a key/cert to the http server creation setup work for you:

https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/66#issuecomment-518810309

We need more defined GitHub issue and then a PR to fix this.

**Comment by anniefu** [comment]
This issue is stale, so I'm going to close it. See comments on https://github.com/GoogleCloudPlatform/functions-framework/issues/35 for workarounds.
