### ISSUE TITLE
Increase --max-http-header-size

### ISSUE THREAD

**Issue by fedemar** [GoogleCloudPlatform/functions-framework-nodejs#74]
Hi all, 

Is there a way to increase the --max-http-header-size like one would do by passing command line arguments to node.

Thanks.

**Comment by squee1945** [comment]
Can you achieve same by setting the value on `NODE_OPTIONS`?

```
NODE_OPTIONS="--max-http-header-size=8192"
```

I believe this only works on Node.js >= 8.15.0

**Comment by fedemar** [comment]
Worked wonderfully! Thank you sir
