### ISSUE TITLE
Install as dev dependency instead

### ISSUE THREAD

**Issue by ricardograca** [GoogleCloudPlatform/functions-framework-nodejs#78]
Shouldn't this be installed as a `devDependency` instead?

Unless I'm missing something, this package is not required to run the code after it's deployed. It's only required for development.

**Comment by GitTom** [comment]
I think that would only hold true for GCF and GCF for Firebase (where I assume it is used under the covers).

For Cloud Run (or any other Knative) where you build your own container, or for local testing, this package is a normal dependency.

**Comment by ricardograca** [comment]
Maybe add that distinction to the docs then?

**Comment by grant** [comment]
So the Functions Framework (FF) is optional.

For the product, Google Cloud Functions, you can do 2 things:
- Not specify any dependency on the FF. Your GCF functions will run as normal.
- Specify a dependency on the FF. This will allow you to run your function locally.

If you specify `devDependency` only, you'll fall into the no-dep-defined bucket above.

---

I tried to find where we could add any docs, and I think we state this pretty clearly here:

https://github.com/GoogleCloudPlatform/functions-framework-nodejs#google-cloud-functions

If there's some place we still should add more information, let us know the specifics and we can re-open this issue.

**Comment by ricardograca** [comment]
Specifically the part that I think could be improved is the [Installation](npm install @google-cloud/functions-framework) section:

> Add the Functions Framework to your package.json file using npm.
>
> `npm install @google-cloud/functions-framework`

This is not true for all uses cases as mentioned above. If you're developing and only using the Functions Framework for testing (read, development) it is a `devDependency`. From what I gathered from the previous comments the only place where it wouldn't be a `devDependency` is in the Cloud Run (or any other Knative) environment.

If you're running a cloud function in your local dev environment you're most likely not interested in having an actual Cloud Function running on your PC and accepting requests. You're just developing, hence `devDependency`.

**Comment by ricardograca** [comment]
For the record, I opted to install it as `devDependency` since I'm only interested in deploying to the Google Cloud Functions platform, and it's only needed for the test suite, therefore it's not a required run time dependency.
