### ISSUE TITLE
Why to use npx after installing

### ISSUE THREAD

**Issue by QuantumInformation** [GoogleCloudPlatform/functions-framework-nodejs#82]
Once you install it with `npm install @google-cloud/functions-framework
`

you can just use an npm script like so

    "emulate:functions": "functions-framework",

instead of

npx @google-cloud/functions-framework

**Comment by grant** [comment]
You don't have to, there are multiple ways to do things in Node.
Do you think there is an advantage to having more steps?

**Comment by QuantumInformation** [comment]
What I meant is that if you use `npx` to run functions-framework, I'm not sure why the docs say to install it.

**Comment by stew-r** [comment]
Use of npx is optional. It's a helpful tool for running a package but it's
an alternative to npm (in some cases) and not a substitute.

**Comment by QuantumInformation** [comment]
Ok, closing thx
