### ISSUE TITLE
Can't get local simulated events unmarshalled correctly after following the latest docs

### ISSUE THREAD

**Issue by ferparra** [GoogleCloudPlatform/functions-framework-nodejs#85]
Hi everyone,

I've been trying to mock a pub/sub event on my local dev according to the docs at https://github.com/GoogleCloudPlatform/functions-framework-nodejs/tree/master/docs#local-testing-of-cloud-events. Nothing special, I'm just trying to manipulate the `data` object passed as a parameter to the function (which I assume should be unmarshalled, given that I'm starting the server with `--signature-type=event`).

Function code:
`exports.helloPubSub = (data, context) => console.log(data);`

Mock Json:
```
{
  "message": {
    "attributes": {
      "key": "value"
    },
    "data": "SGVsbG8gQ2xvdWQgUHViL1N1YiEgSGVyZSBpcyBteSBtZXNzYWdlIQ==",
    "messageId": "136969346945"
  },
  "subscription": "projects/myproject/subscriptions/mysubscription"
}
```

Output
```
{
  '{  "message": {    "attributes": {      "key": "value"    },    "data": "SGVsbG8gQ2xvdWQgUHViL1N1YiEgSGVyZSBpcyBteSBtZXNzYWdlIQ': '=",    "messageId": "136969346945"  },  "subscription": "projects/myproject/subscriptions/mysubscription"}'
```

All of the above is pretty standard. However, I can't get to parse the resulting object in any meaningful way.

Would you be able to shed some light on this issue?

**Comment by grant** [comment]
Hi @ferparra,
Can you try this guide and report any errors (if any) that you face?
https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/docs/events.md

**Comment by ferparra** [comment]
Hi @grant. The example of the above is based on following that exact guide you just shared.

There are no errors. Just either `undefined`, when trying to `console.log` any of the keys, or the object type described as the output, which appears to split the data string value by `=`.

**Comment by grant** [comment]
As @ericnorris stated (thanks!), you need to provide the `application/json` content type header to the request to properly send the request.

I've updated the guide to make the testing instructions clear.
