### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by willdurand** [GoogleCloudPlatform/functions-framework-nodejs#86]
The `--source` option looks great, could you please release a new version of this lib so that we can use this new feature? Thanks!

**Comment by grant** [comment]
@hdp617 to push a new version.
N.B. We should configure auto-releases.

**Comment by grant** [comment]
> Ok, I've pushed a PR for a new release. What are the options for auto-releases?

The Yoshi team has more details on release tooling.

See these docs:
- go/yoshi-nodejs-playbook
- https://github.com/googleapis/releasetool

...and contact Justin for more information to see if this tool could be an option.
