### ISSUE TITLE
How to point to local datastore (using gcloud beta emulators datastore)?

### ISSUE THREAD

**Issue by QuantumInformation** [GoogleCloudPlatform/functions-framework-nodejs#87]
I import the following in my cloud functions and am trying to run it all locally with the functions framework

 ` ds: require('@google-cloud/datastore')(),`

By default ds.baseUrl_ is "datastore.googleapis.com", but when running `gcloud beta emulators datastore` the local store is at `http://localhost:8766/`

my scripts which fire up both emulation:

```
  "emulate:datastore": "gcloud beta emulators datastore start --project realworldgcp",
    "emulate:functions": " forever -c 'node --inspect' node_modules/@google-cloud/functions-framework --target=api ",
```

How do I  update this baseUrl_ when running with FF?

<img width="677" alt="Screenshot 2019-09-11 at 08 05 26" src="https://user-images.githubusercontent.com/216566/64699168-1becc800-d49c-11e9-9ae0-37dab22b1c21.png">

**Comment by grant** [comment]
I think this would be a good question for the datastore repo:

https://github.com/googleapis/nodejs-datastore

The FF is not much different than raw Node w.r.t. this question.

**Comment by QuantumInformation** [comment]
Will do thx

**Comment by QuantumInformation** [comment]
All this will make some good videos for youtube soon!

**Comment by QuantumInformation** [comment]
Here is the video showing how to set it up

https://www.youtube.com/watch?v=foQLf5BBF2Q&t=28s
