### ISSUE TITLE
The "path" argument must be of type string. Received type undefined @1.3.0

### ISSUE THREAD

**Issue by jpbarbosa** [GoogleCloudPlatform/functions-framework-nodejs#89]
```
npx @google-cloud/functions-framework --target=helloWorld
The "path" argument must be of type string. Received type undefined
```

I notice the problem at version 1.3.0. At version 1.2.1 the command runs normally.

My system is MacOS 10.14.6, with Node 10.16.3 installed with Homebrew.

**Comment by dfanchon** [comment]
Having the same issue here with a cloud build deployment.

**Comment by timswalling** [comment]
When I add `--source=./` to the arguments it removes the error message but I then get a 404 (`Cannot GET /`) when trying to trigger the function

**Comment by yvmarques** [comment]
I got the same error, and I fixed with the following flag at the start script.

`functions-framework --target=functionName --source='./'`

I guess @timswalling  you need to enclose the `./` with quotes in order to have a string

**Comment by hdp617** [comment]
I'm sorry for this bad release. I'll make a new release soon. In the mean time, you can remove functions-framework as a dependency in your `package.json` when you deploy to GCF. I think it will fix this issue.
