### ISSUE TITLE
FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing.

### ISSUE THREAD

**Issue by abhirajdevelopment** [GoogleCloudPlatform/functions-framework-nodejs#95]
I'm getting the below error:

$ npx @google-cloud/functions-framework --target=login
Warning, FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing. Initializing firebase-admin will fail
Function 'login' is not defined in the provided module.
Did you specify the correct target function to execute?
Could not load the function, shutting down.

I have node version 12.9.1 installed. Here's my package.json

"engines": {
    "node": "8"
  },
  "dependencies": {
    "@google-cloud/functions-framework": "1.2.1",
    "@google-cloud/logging": "5.2.1",
    "busboy": "^0.3.1",
    "express": "4.17.1",
    "firebase": "6.4.0",
    "firebase-admin": "8.3.0",
    "firebase-functions": "3.1.0"
  },

Is there something I'm missing? How do I fix this?

**Comment by grant** [comment]
There seems to be a few issues with your setup:
- Your application is missing the environment variables `FIREBASE_CONFIG` and `GCLOUD_PROJECT`. You need to set them up before starting.
- Your file `index.js` must have `exports.function = ...`.

If you still have trouble setting up Firebase, you might want to file an issue here:
https://github.com/firebase/firebase-admin-node

Closing this issue, but feel free to comment.
