### ISSUE TITLE
Event parsing doesn't match Cloud Functions in background mode

### ISSUE THREAD

**Issue by ericnorris** [GoogleCloudPlatform/functions-framework-nodejs#96]
Hey there!

Related to #41 and #85, I ran into a lot of confusion trying to sort out what the format should be for the request body to a local [background function](https://cloud.google.com/functions/docs/writing/background).

In production a background function has the following for the first parameter:

```
{ @type: 'type.googleapis.com/google.pubsub.v1.PubsubMessage',
  attributes: null,
  data:  '<base64 data>' }
```

and the following for the "context" parameter:

```
{ eventId: '749799261766789',
  timestamp: '2019-09-17T19:56:09.018Z',
  eventType: 'providers/cloud.pubsub/eventTypes/topic.publish',
  resource: '<pubsub topic>' }
```

The [current docs](https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/de6ef3874ae703084d5b7566ecde743a8f80bd36/docs/events.md) for using the functions framework for events suggests `curl`ing data in a format that results in the parameters not matching the above - the first parameter becomes:

```
{ message:
   { attributes: {},
     data: '<base64 data>',
     messageId: '136969346945' },
  subscription: 'projects/myproject/subscriptions/mysubscription' }
```

And the "context" parameter:

```
{ type: 'true',
  specversion: 'true',
  source: 'true',
  id: 'true' }
```

Digging into the source code, https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/de6ef3874ae703084d5b7566ecde743a8f80bd36/src/invoker.ts#L431-L447 seems to expect the body (for "legacy events") to look something like:

```
{ data:
  { data: '<base64 data>`,
    attributes: null,
    @type: 'type.googleapis.com/google.pubsub.v1.PubsubMessage' },
  eventId: 749799261766789 }
```

(Further evidence this is expected is in this [WIP branch](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/1255/files#diff-a5c7e60c1ae9d8d39557244c08a97e48R47) for NodeJS samples.)

Using the above POST body seems to result in function parameters that most closely match production, and although it doesn't match [the POST body for push messages](https://cloud.google.com/pubsub/docs/push#receiving_push_messages) I'm assuming that's what users should send if they want their function to act closest to what they will see when they deploy to Cloud Functions.

Is this correct?

**Comment by grant** [comment]
I'm not sure the expected behavior in this case to be honest.
@ace-n Do you know more about event parsing in GCF background functions?

**Comment by ace-n** [comment]
cc @mogar1980 @swalkowski

**Comment by swalkowski** [comment]
The Functions Framework supports multiple event formats:

- The [doc](https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/de6ef3874ae703084d5b7566ecde743a8f80bd36/docs/events.md) that you mentioned describes handling events conforming to the [CloudEvents](https://cloudevents.io/) spec, in structured or binary mode.
- However, Google Cloud Functions service currently does not provide events in CloudEvents format. Instead, it uses the structured JSON format in one of the following forms:
  - "data" and "context" attributes.
  - "data" attribute and individual context attributes inlined at the top level, next to "data" (the legacy format).

If you want to trigger your function with CloudEvents, which may be useful for integrations beyond Cloud Functions, use the CloudEvents format.

But if you want to trigger the function like a [background function](https://cloud.google.com/functions/docs/writing/background) in Cloud Functions service, use one of the other formats mentioned above.

We should clarify this in the Functions Framework docs.

**Comment by burtonjc** [comment]
@swalkowski, I posted [a comment on this issue](https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/41#issuecomment-544054901) too explaining the behavior I am seeing, but it seems related to this issue as well.

What I am trying to accomplish is a local dev environment where:
1. `functions-framework` is serving a GCF pubsub triggered function locally
1. gcloud PubSub emulator is running locally
1. There is a push subscription in the emulator with a push endpoint to the functions-framework server
1. Then publish messages to the subscription topic to trigger the function

**Expected behvior**: the function is executed with arguments similar to those it receives while running in GCF.

**Actual behavrior**: the function is executed with the first argument being `undefined` and the second like:
```
{
    "subscription": "projects/gcp-nodejs-demo/subscriptions/local-receivePubSub-demo",
    "message": {
        "data": "<encoded string",
        "messageId": "1",
        "attributes": { "transactionId":"72c28439-5c5d-4e59-a032-e8f622785835" }
    }
}
```

Is this a problem with the emulator not sending the same message format as production PubSub does? Or is it a problem with how `functions-framework` is parsing the event?

**Comment by m0ar** [comment]
@burtonjc Did you find any solutions for this issue? Pains us as well trying to setup a local devenv for cloud functions.

**Comment by burtonjc** [comment]
@m0ar, unfortunately no, at least not anything elegant. You already commented on it, but there is some good conversation on https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/41 as well.

**Comment by grant** [comment]
Here's a sample integration test using the `event` parsing for Cloud Functions in background mode for Pub/Sub:

https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/functions/helloworld/test/sample.integration.pubsub.test.js

We have lots of other samples for GCF too in that repo.
We don't use the Pub/Sub emulator, that may be a source of a problem.
