### ISSUE TITLE
Does Functions Framework Run Functions Persistently?

### ISSUE THREAD

**Issue by jon-malave** [GoogleCloudPlatform/functions-framework-nodejs#97]
I am currently using Google Cloud Functions, but we need better performance (response time) for our application. 

If I install Functions Framework on a Cloud VM Instance and serve my functions from this Instance will the functions stay warm (no need to re-install packages on each function invocation)? 

Also, can I serve all of my functions on the same port number, or does each function require seperate port?

**Comment by grant** [comment]
> If I install Functions Framework on a Cloud VM Instance and serve my functions from this Instance will the functions stay warm (no need to re-install packages on each function invocation)?

I haven't used Cloud VM Instances to be honest. I believe warmup requests would definitely help. The Functions Framework is a light wrapper around Express, which is built on Node's native modules like `http` and `fs`.

> Also, can I serve all of my functions on the same port number, or does each function require seperate port?

Node requires web servers to be on separate ports. There are some workarounds discussed here: #23.

We also have a handy video here if you haven't seen it for Functions:
https://www.youtube.com/watch?v=IOXrwFqR6kY

---

LMK if you have other questions.

**Comment by grant** [comment]
> under the hood Express is running the index.js persistently with all the required dependencies. That would mean the function is always warm no? Correct me if i'm wrong.

Your function is in a container hosted on Google Cloud. If there's more demand for your function, Google will spin up more instances to ensure traffic to your function is OK. Sometimes there is 0 traffic, in which case we will not have a warm/persistent instance.

Sometimes you get more traffic than normal, requiring Google to allocate new containers running the functions framework.

**Comment by jon-malave** [comment]
> > under the hood Express is running the index.js persistently with all the required dependencies. That would mean the function is always warm no? Correct me if i'm wrong.
> 
> Your function is in a container hosted on Google Cloud. If there's more demand for your function, Google will spin up more instances to ensure traffic to your function is OK. Sometimes there is 0 traffic, in which case we will not have a warm/persistent instance.
> 
> Sometimes you get more traffic than normal, requiring Google to allocate new containers running the functions framework.

Thanks grant! I appreciate the response.
